const a=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const P=require('./account-personal-model.js');
const db={settings:{targetWeight:90,targetCalories:2850,targetProtein:150},daily:{'2026-09-10':{weight:80},'2026-09-20':{weight:84}},trainingLogs:{}};
a.equal(P.targets(db,'2026-09-16'),null,'sample/default settings are not personal targets');
a.equal(P.weight(db,'2026-09-16').kg,80,'future weight is excluded');
a.equal(P.weight({settings:{targetWeight:90}},'2026-09-16'),null,'goal weight is not observed weight');
db.settings.personalTargets={kcal:2400,proteinG:140,fatG:80,waterL:'2,5'};
const t=P.targets(db,'2026-09-16');
a.equal(t.carbsG,280);a.equal(t.macroKcal,2400);a.equal(t.waterL,2.5);a.equal(t.carbsGkg,3.5);a.equal(t.kind,'user-defined');a.equal(t.sportEnergyEstimate,null);
for(const changes of [{kcal:''},{waterL:-1},{kcal:500,proteinG:200},{fatG:'abc'}])a.throws(()=>P.validate({...db.settings.personalTargets,...changes}));
const sandbox={db,ALOSAccount:{user:{id:'synthetic'}},ALOSRuntime:{getDb:()=>db},AccountPersonalModel:P};sandbox.window=sandbox;
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('adaptive-nutrition-engine.js','utf8'),sandbox);
a.equal(sandbox.AdaptiveNutrition.targets('2026-09-16').kcal,2400);
delete db.settings.personalTargets;a.equal(sandbox.AdaptiveNutrition.targets('2026-09-16'),null);
vm.runInContext(fs.readFileSync('load-prescription-engine.js','utf8'),sandbox);
a.equal(sandbox.LoadPrescriptionEngine.recommend('OHP','3 x 8','2026-09-16').source,'missing-personal-baseline');
a.equal(sandbox.LoadPrescriptionEngine.recommend('OHP').value,null);
sandbox.PainIntelligence={exerciseAdvice:()=>({level:3})};
a.equal(sandbox.LoadPrescriptionEngine.recommend('OHP').source,'pain_guard','pain takes precedence');
delete sandbox.PainIntelligence;db.characterData={ohpKg:30};
a.equal(sandbox.LoadPrescriptionEngine.recommend('OHP').source,'capability_anchor','explicit personal baseline remains usable');
delete sandbox.ALOSAccount;delete db.characterData;
a.equal(sandbox.LoadPrescriptionEngine.recommend('OHP').source,'bodyweight_baseline','legacy behavior is preserved');
console.log('PASS: no inherited personal targets, observed weight, consistent macros, missing-load baseline and pain priority.');
