const CACHE="athlete-life-os-v10-1-0-period-calendar";
const MODEL_CACHE="athlete-life-body-model-v1";
const CORE=["./","./index.html","./styles.css","./app.js","./server-sync.js","./durable-persistence.js","./exercise-knowledge-library.js","./load-prescription-engine.js","./load-prescription-rules.json","./physiological-impact-engine.js","./physiological-impact-evidence.json","./movement-intelligence-engine.js","./ad-hoc-session-engine.js","./pain-intelligence-core.js","./pain-intelligence-engine.js","./pain-intelligence-rules.json","./guided-workout-core.js","./substitution-intelligence-core.js","./guided-workout-engine.js","./movement-science-evidence.json","./capability-catalog.js","./athlete-profile-engine.js","./nutrition-impact-engine.js","./rest-interval-engine.js","./rest-interval-evidence.json","./nutrition-impact-evidence.json","./athlete-profile-library.json","./nutrition-library.js","./periodic-trend-engine.js","./nutrition-ledger-engine.js","./water-ledger-engine.js","./hydration-intelligence-engine.js","./hydration-intelligence-evidence.json","./nutrition-record-engine.js","./health-state-engine.js","./nutrition-library-meta.json","./bodymap3d.js","./adaptive-intelligence.js","./record-manager.js","./adherence-engine.js","./gap-reconciliation.js","./backup-vault.js","./system-integrity-engine.js","./architecture-bootstrap.js","./release-integrity-v8.js","./sports-science-policy.js","./adaptive-coach-solver.js","./canonical-session-engine.js","./adaptive-nutrition-engine.js","./tissue-load-engine.js","./personal-calibration-engine.js","./performance-trend-v2.js","./event-store-engine.js","./schema-migration-engine.js","./data-lineage-engine.js","./engine-bus.js","./training-mesh-dashboard.js","./exercise-library.json","./science-library.json","./manifest.json"];
CORE.push("./training-session-service.js","./athlete-coordinator.js","./training-periods.js");
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)))});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&k!==MODEL_CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener("fetch",e=>{
 const url=new URL(e.request.url);if(e.request.method!=="GET"||url.pathname.startsWith("/api/"))return;
 if(url.origin===location.origin&&url.pathname.endsWith("/assets/caglar-body.glb")){
  e.respondWith(caches.open(MODEL_CACHE).then(async c=>{const cached=await c.match(e.request);if(cached)return cached;const r=await fetch(e.request);if(r.ok){const saved=c.put(e.request,r.clone()).catch(()=>{});e.waitUntil(saved);}return r;}));return;
 }
 e.respondWith(fetch(e.request).then(r=>{if(r.ok&&url.origin===location.origin){const copy=r.clone();e.waitUntil(caches.open(CACHE).then(c=>c.put(e.request,copy)).catch(()=>{}));}return r;}).catch(()=>caches.match(e.request,{ignoreSearch:true})));
});
