const assert=require('node:assert/strict');
const C=require('./sport-catalog.js'),K=require('./sports-profile-core.js');
const today='2026-09-16',now='2026-09-16T12:00:00Z';
assert.equal(new Set(C.sports.map(s=>s.id)).size,C.sports.length);
assert(C.sports.length>=190);assert.equal(Object.keys(C.families).length,15);
assert.equal(new Set(C.methods.map(s=>s.id)).size,C.methods.length);
for(const sport of C.sports){assert(C.families[sport.family]);assert(C.schemas[sport.schema]);assert.equal(sport.support,'record-summary');}
assert(C.search('yuzme').some(s=>s.id==='swimming'));assert(C.search('SWIMMING').some(s=>s.id==='swimming'));
assert(C.search('tirmanis','adaptive').some(s=>s.id==='para-climbing'));
assert.equal(K.parseDate('10.09.2026'),'2026-09-10');assert.equal(K.parseDate('31.09.2026'),null);
assert.equal(K.parseDate('29.02.2026'),null);assert.equal(K.parseDate('29.02.2028'),'2028-02-29');
const profile={sports:[{sportId:'swimming',experience:'new'},{sportId:'calisthenics',experience:'regular'}],goals:['hybrid'],methods:['technique'],equipment:['pool','bodyweight'],availability:[45,0,45,0,60,0,0]};
assert.deepEqual(K.validateProfile(profile),[]);
for(const invalid of [{sports:[]},{goals:[]},{availability:[0,0,0,0,0,0,0]},{availability:[-5,0,0,0,0,0,0]},{availability:[NaN,0,0,0,0,0,0]},{availability:[46,0,0,0,0,0,0]},{methods:['invented']},{sports:[{sportId:'missing',experience:'new'}]}])assert(K.validateProfile({...profile,...invalid}).length);
const custom=K.customSport('Kişisel denge parkuru','gymnastics','attempts');
assert(C.find(custom.id,[custom]));assert.throws(()=>K.customSport('Yüzme','invalid','general'));
assert.throws(()=>K.customSport('Havuz yüzmesi','water','swimming'),/kütüphanede/);
const state={trainingLogs:{'2026-09-10':[{id:'legacy',sets:[8,8]}]},trainingPeriods:[{id:'plan',startDate:'2026-09-01',endDate:'2026-11-30',weekly:[[],[{name:'Pull-Up'}],[],[],[],[],[]]}],unknown:{retained:true}};
const original=JSON.stringify(state);
const first=K.applyProfile(state,profile,[custom],now);assert.equal(JSON.stringify(state),original);
Object.assign(state,first);
const changed=K.applyProfile(state,{...profile,sports:[{sportId:'football',experience:'returning'}]},[],now);
assert.equal(changed.athleteProfileHistory.length,1);assert.equal(changed.athleteProfileHistory[0].profile.sports[0].sportId,'swimming');
assert.equal(changed.customSports[0].id,custom.id);assert.equal(changed.athleteProfile.createdAt,first.athleteProfile.createdAt);
assert(K.context(state,'2026-09-15').notes.some(n=>n.includes('Salı')));
assert.equal(K.context(state,'2026-09-14').availableMinutes,45);
assert.equal(K.context(state,'2026-09-15').availableMinutes,0);
assert.equal(K.context(state).coverage.physiologyIntegration,false);
const input={sportId:'swimming',date:'10.09.2026',durationMin:'40',effort:'5',methodId:'technique',metrics:{distanceM:'1000',movingMinutes:'20',poolLengthM:'25'},notes:'Test'};
const parsed=K.validateSession(input,[],today);
assert.equal(parsed.date,'2026-09-10');assert.equal(K.sessionDetails(parsed)[0].value,2);
assert.deepEqual(K.sessionDetails({...parsed,metrics:{distanceM:1000}}),[],'do not infer pace from time including rests');
for(const changes of [{date:'17.09.2026'},{date:'30.02.2026'},{durationMin:'Infinity'},{durationMin:''},{effort:'11'},{metrics:{movingMinutes:41}},{metrics:{distanceM:-1}}])assert.throws(()=>K.validateSession({...input,...changes},[],today));
assert.throws(()=>K.validateSession({...input,sportId:'archery',metrics:{attempts:10,hits:11}},[],today));
assert.throws(()=>K.validateSession({...input,sportId:'bouldering',metrics:{attempts:3.5}},[],today));
assert.equal(K.validateSession({...input,effort:'',metrics:{}},[],today).effort,null);
for(const sport of C.sports){const row=K.validateSession({...input,sportId:sport.id,metrics:{}},[],today);assert.equal(row.sportName,sport.name);}
let patch=K.applySession(state,input,{today,now});Object.assign(state,patch);
const row=state.sportSessions[0],before=JSON.stringify(state);
const update=K.applySession(state,{...input,date:'11.09.2026',durationMin:45},{id:row.id,expected:JSON.stringify(row),today,now});
assert.equal(JSON.stringify(state),before);assert.equal(update.sportSessions.length,1);
assert.equal(update.sportSessions[0].createdAt,row.createdAt);assert.equal(update.sportSessions[0].id,row.id);
assert.equal(update.sportSessionHistory[0].record.date,'2026-09-10');
assert.throws(()=>K.applySession(state,input,{id:row.id,expected:'stale',today,now}),/değişti/);
Object.assign(state,update);
Object.assign(state,K.applySession(state,{...input,sportId:'running',date:'11.09.2026',durationMin:30,metrics:{distanceKm:5,movingMinutes:30}},{today,now}));
assert.equal(K.summary(state,{to:today}).sessions,2);assert.equal(K.summary(state,{to:today}).minutes,75);
assert.equal(K.summary(state,{sportId:'swimming',to:today}).bySport[0].distanceM,1000);
assert.equal(K.summary(state,{from:'2026-09-12',to:today}).sessions,0);
assert.deepEqual(state.trainingLogs,JSON.parse(original).trainingLogs);assert.deepEqual(state.trainingPeriods,JSON.parse(original).trainingPeriods);

// Exercise the shared backup path as actually shipped, including imports into nonempty profiles.
const {ctx}=require('./integration-v9.test.js');
assert(ctx.ALOSDurablePersistence.weight({athleteProfile:first.athleteProfile})>0,'profile-only data is meaningful');
assert(ctx.ALOSDurablePersistence.weight({sportSessions:state.sportSessions})>0,'sport-only data must not trigger empty-state recovery');
const incoming={athleteProfile:changed.athleteProfile,sportSessions:[{...state.sportSessions[0],notes:'imported'},{...state.sportSessions[0],id:'another'}],customSports:[{...custom,id:'custom:second'}],sportSessionHistory:update.sportSessionHistory};
const merged=ctx.BackupVault.mergeDB(state,incoming);
assert.equal(merged.sportSessions.length,3);assert.equal(merged.sportSessions.find(r=>r.id===row.id).notes,'imported');
assert.equal(merged.customSports.length,2);assert.equal(merged.athleteProfile.sports[0].sportId,'football');
assert(merged.athleteProfileHistory.some(r=>r.profile.sports[0].sportId==='swimming'));
const again=ctx.BackupVault.mergeDB(merged,incoming);
assert.equal(again.sportSessions.length,3);assert.equal(again.athleteProfileHistory.length,merged.athleteProfileHistory.length);
assert.equal(JSON.stringify(ctx.BackupVault.normalizeForApp(merged).sportSessions),JSON.stringify(merged.sportSessions));
console.log('PASS: 199-activity catalogue, profile validation/history, sport metrics and dates, edit conflicts, manual-plan preservation and backup merge.');
