const a=require('node:assert/strict');
require('./entry-fields-core');require('./personal-health-core');global.HealthCore=require('./health-core');
const C=require('./sport-catalog'),K=require('./sports-profile-core'),W=require('./athlete-workspace-core'),T=require('./training-planner-core');
const today='2026-09-16';
let db={personalHealthProfile:{birthDate:'1990-01-01'},athleteProfile:{sports:[{sportId:'calisthenics',experience:'new'}],availability:[45,0,45,0,45,0,0],equipment:['bodyweight','pullup']}};
const answers={sportId:'calisthenics',experience:'new',objective:'strength',minutes:45,adult:'yes',weeks:4,startDate:today,target:'Kontrollü barfiks geliştirmek',focus:'barfiks',equipment:['bodyweight','pullup'],days:[0,2,4]};
for(const sport of C.all()){
 const p=T.draft(db,{...answers,sportId:sport.id},today);
 const review=W.reviewPeriod(db,p,today);a.equal(review.period.blocks.length,3);a.equal(review.period.weeks,4);
 a.deepEqual(review.period.restDays,[1,3,5,6]);a.ok(p.planner.coverage);a.equal(db.multisportPeriods,undefined);
}
a.throws(()=>T.draft(db,{...answers,days:[]},today));a.throws(()=>T.draft(db,{...answers,days:[0,1,2,3,4,5,6]},today));
a.throws(()=>T.draft(db,{...answers,weeks:5},today));
const draft=T.draft(db,answers,today);a.ok(draft.blocks[0].steps.some(s=>s.name==='Assisted Pull-Up'));a.ok(draft.blocks[0].steps.every(s=>s.type==='resistance'));
a.equal(T.suggestion({}, {...answers,adult:'no'}).steps.length,0);
a.equal(T.suggestion({personalHealthProfile:{birthDate:'2012-01-01'}}, answers).steps.length,0);
a.equal(T.suggestion(db,{...answers,sportId:'freediving'}).coverage,'calendar-only');
Object.assign(db,W.activate(db,draft,today));const period=db.multisportPeriods[0];a.equal(db.settings.pinnedPeriodId,period.id);a.deepEqual(period.planner.restDays,[1,3,5,6]);
const block=W.planned(db,today)[0];Object.assign(db,T.startRun(db,block,today,1000));a.throws(()=>T.startRun(db,block,today));a.equal(db.sportSessions,undefined);
a.equal(T.elapsed(db.activeWorkoutRun,31000),30000);const initial=db.activeWorkoutRun;
Object.assign(db,T.updateRun(db,{status:'paused'},initial,31000));a.equal(T.elapsed(db.activeWorkoutRun,90000),30000);
a.throws(()=>T.updateRun(db,{status:'running'},initial,90000),/değişti/);
Object.assign(db,T.updateRun(db,{status:'running'},db.activeWorkoutRun,90000));a.equal(T.elapsed(db.activeWorkoutRun,91000),31000);
const s=block.steps[0];a.throws(()=>T.updateRun(db,{actual:[{stepId:s.id,index:0,done:true}]},db.activeWorkoutRun),/tekrar/);
Object.assign(db,T.updateRun(db,{actual:[{stepId:s.id,index:0,done:true,reps:s.reps,loadKg:0,rir:3}]},db.activeWorkoutRun,91000));
db=JSON.parse(JSON.stringify(db));a.equal(db.activeWorkoutRun.actual[0].done,true);a.equal(db.activeWorkoutRun.steps.length,block.steps.length);
a.throws(()=>T.archivePeriod(db,period.id,today),/Önce açık/);
const finish=T.finishRun(db,{durationMin:31.5,effort:4,conditions:'aynı teknik'},db.activeWorkoutRun,today);Object.assign(db,finish);
a.equal(db.sportSessions.length,1);a.equal(db.sportSessions[0].workout.recordedSets,1);a.equal(db.trainingLogs[today].length,1);a.equal(db.activeWorkoutRun,null);a.equal(db.workoutRunHistory.length,1);
a.throws(()=>T.startRun(db,block,today),/zaten/);a.throws(()=>T.finishRun(db,{durationMin:30},{id:'x'},today));
Object.assign(db,T.saveGoal(db,{type:'weight',title:'Kilo hedefim',startDate:today,targetDate:'2026-10-14',baseline:'80,5',target:78},null,today));let goal=db.athleteGoals[0];
Object.assign(db,T.measurement(db,goal.id,80,'2026-09-17','2026-09-17'));a.equal(db.bodyMeasurements.at(-1).weight,80);
let status=T.goalStatus(db,goal,'2026-09-17');a.equal(status.trend,'toward');a.equal(status.current,80);a.equal(status.progress,20);a.equal(status.points.length,2);
Object.assign(db,T.measurement(db,goal.id,81,'2026-09-18','2026-09-18'));a.equal(T.goalStatus(db,goal,'2026-09-18').trend,'away');
a.throws(()=>T.measurement(db,goal.id,70,'2026-09-19','2026-09-18'));
Object.assign(db,T.saveGoal(db,{type:'movement',title:'Çömelme hedefi',sportId:'calisthenics',movement:s.name,metric:'reps',unit:'tekrar',conditions:'aynı teknik',startDate:today,targetDate:'2026-10-14',baseline:4,target:10},null,today));goal=db.athleteGoals[1];
a.equal(T.goalStatus(db,goal,today).current,s.reps);a.equal(T.goalStatus(db,{...goal,conditions:'farklı koşul'},today).current,4);
db.daily={[today]:{sleepTime:'23:00',wakeTime:'07:00',nightAwake:0}};db.foodLogs={[today]:[{kcal:500}]};
const summary=T.overview(db,7,today);a.equal(summary.sleep.count,1);a.equal(summary.sleep.average,480);a.equal(summary.nutrition.recordedDays,1);a.equal(summary.nutrition.averageKcal,500);a.equal(summary.recorded,1);a.equal(summary.actualSets,1);
Object.assign(db,T.archivePeriod(db,period.id,'2026-09-17'));a.equal(W.planned(db,'2026-09-18').length,0);a.equal(W.planned(db,today).length,1);a.equal(db.sportSessions.length,1);a.equal(db.multisportPeriods.length,1);a.equal(db.settings.pinnedPeriodId,null);
const future=T.draft(db,{...answers,startDate:'2026-09-18'},today);a.ok(W.activate(db,future,today));
// Removing a plan after today's completed session must preserve its editable link.
let sameDay=JSON.parse(JSON.stringify(db));sameDay.multisportPeriods[0].archivedOn=null;
Object.assign(sameDay,T.archivePeriod(sameDay,period.id,today));a.equal(W.planned(sameDay,today).length,1);
a.ok(W.validatePlanLink(sameDay,sameDay.sportSessions[0]));a.equal(W.planned(sameDay,'2026-09-18').length,0);
a.equal(T.goalStatus(db,db.athleteGoals[1],today).hasMeasurement,true);a.equal(T.goalStatus(db,db.athleteGoals[1],'2026-09-15').current,null);
Object.assign(db,T.saveGoal(db,{type:'sport',title:'Yüzme mesafem',sportId:'swimming',sportMetric:'distanceM',unit:'m',conditions:'25 m havuz',discipline:'Serbest',startDate:today,targetDate:'2026-10-14',baseline:500,target:1000},null,today));
const swimGoal=db.athleteGoals.at(-1);db.sportSessions.push({sportId:'swimming',date:today,conditions:'25 m havuz',discipline:'Serbest',metrics:{distanceM:750}});
a.equal(T.goalStatus(db,swimGoal,today).current,750);a.equal(T.goalStatus(db,{...swimGoal,discipline:'Sırtüstü'},today).current,500);
console.log('PASS guided drafts for '+C.all().length+' sports, explicit adoption/rest days, health scope, resumable timer/sets, goal trends, shared evidence, archival history and replacement period.');
