const fs=require('fs'),vm=require('vm'),assert=require('assert');
const app=fs.readFileSync('app.js','utf8');
const guided=fs.readFileSync('guided-workout-engine.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
assert(app.includes('ATHLETE_PROGRAM_MICROCYCLE_V92'),'single Program Engine microcycle exists');
assert(app.includes('1:{type:"pull",name:"Pull + Front Lever"}'),'Monday pull fixed');
assert(app.includes('2:{type:"run",name:"Easy / Aerobic Run"}'),'Tuesday run fixed');
assert(app.includes('3:{type:"push",name:"Push + Planche"}'),'Wednesday push fixed');
assert(app.includes('5:{type:"legs",name:"Legs + Hybrid"}'),'Friday legs fixed');
assert(app.includes('programEngineVersion:"9.2"'),'plans carry Program Engine version');
assert(app.includes('Kontrollü erteleme'),'hard constraints use explicit controlled deferral');
assert(app.includes('programPhaseLoadV92'),'12-week phase modulates dose');
assert(guided.includes('AthleteProgramEngine?.build?.(14,"guided_runner_start")'),'Runner refreshes unified engine before starting');
assert(guided.includes('const VERSION="9.2"'),'Runner version bumped');
assert(html.includes('app.js?v=10.1.0')&&html.includes('guided-workout-engine.js?v=10.1.0'),'browser cache-busting versions updated');
assert(/const CACHE="athlete-life-os-v\d+-\d+-\d+-[\w-]+"/.test(sw),'service worker must have a versioned cache');
const ctx={window:{db:{daily:{},trainingLogs:{},foodLogs:{},water:{},settings:{targetWeight:70,targetCalories:2800,targetWater:3}},EXERCISE_KNOWLEDGE:{A:{qualities:{skill:1,hypertrophy:5,strength:5}},B:{qualities:{skill:10,hypertrophy:10,strength:10}}},EXERCISE_SCIENCE:{},V5_EXERCISE_MUSCLES:{},NutritionLedger:{totals:()=>({})},NUTRITION_LIBRARY:[]}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('sports-science-policy.js','utf8'),ctx);
assert.equal(ctx.window.SportsSciencePolicy.version,'9.2');
const t={items:[["A","3×8","first"],["B","3×8","second"]]};
const opt=ctx.window.SportsSciencePolicy.optimizeTemplate('2026-09-15','push',t);
assert.deepStrictEqual(JSON.parse(JSON.stringify(opt.items)),t.items,'science audit must preserve programmed exercise order');
assert.equal(opt.scienceAudit.policy,'stable_program_continuity');
console.log('v9.2 unified Program Engine tests: PASS');
