const fs=require('fs'),assert=require('assert');
const app=fs.readFileSync('app.js','utf8'),idx=fs.readFileSync('index.html','utf8'),vault=fs.readFileSync('backup-vault.js','utf8'),sw=fs.readFileSync('service-worker.js','utf8');
assert(app.includes('function persistWeeklyScheduleFromUI'),'weekly persistence function missing');
assert(app.includes('weekly-autosave'),'weekly autosave missing');
assert(app.includes('window.ALOSFlushPendingUIState'),'pending UI flush missing');
assert(app.includes('beforeunload')&&app.includes('pagehide'),'close-time flush missing');
assert(idx.includes('id="saveWeekBtn"')&&idx.includes('id="weekSaveStatus"'),'explicit weekly save UI missing');
assert(vault.includes('ALOSFlushPendingUIState?.("pre-backup-flush")'),'backup does not flush open weekly form');
assert(idx.includes('app.js?v=10.0.0')&&idx.includes('backup-vault.js?v=10.0.0'),'cache bust missing');
assert(sw.includes('athlete-life-os-v10-0-0-dynamic-sqlite'),'service-worker cache not bumped');
console.log('PASS weekly persistence v9.2.8');
