/* Account wellness pages use the existing durable snapshot and account authority. */
(()=>{
'use strict';if(!window.ALOSAccount)return;
const H=window.HealthCore,q=id=>document.getElementById(id),db=()=>window.ALOSRuntime.getDb();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n===null||n===undefined?'—':Number(n).toLocaleString('tr-TR',{maximumFractionDigits:2});
const labfmt=H.formatValue,tickfmt=n=>Number(n).toLocaleString('tr-TR',{maximumSignificantDigits:3});
const date=d=>String(d).split('-').reverse().join('.'),hours=n=>n===null?'—':`${Math.floor(Math.round(n)/60)} sa ${Math.round(n)%60} dk`;
const fasting=v=>({fasting:'Açlık',nonfasting:'Tokluk',unknown:'Açlık durumu belirtilmemiş'})[v]||'Belirtilmemiş';
const ref=r=>r.low===null&&r.high===null?'Belirtilmedi':r.low===null?'≤ '+labfmt(r.high):r.high===null?'≥ '+labfmt(r.low):labfmt(r.low)+' – '+labfmt(r.high);
const header=(eyebrow,title,detail)=>`<header class="wellness-header"><p class="sports-eyebrow">${eyebrow}</p><h2>${title}</h2><p>${detail}</p></header>`;
const metric=(v,l)=>`<div><strong>${v}</strong><span>${l}</span></div>`;
function nav(root){root.querySelectorAll('[data-wellness-page]').forEach(b=>b.onclick=()=>AthleteWorkspace.navigate(b.dataset.wellnessPage))}
function chart(points,{label,unit,low=null,high=null}={}){
 const known=points.filter(p=>p.value!==null&&Number.isFinite(p.value));
 if(!known.length)return '<p class="wellness-empty">Grafik için henüz ölçüm yok.</p>';
 const values=known.map(p=>p.value),min=Math.min(...values,...[low,high].filter(v=>v!==null)),max=Math.max(...values,...[low,high].filter(v=>v!==null)),pad=Math.max((max-min)*.15,Math.abs(max)*.05,.1),bottom=Math.max(0,min-pad),top=max+pad;
 const first=Date.parse(points[0].date),last=Date.parse(points.at(-1).date),x=p=>60+((Date.parse(p.date)-first)/(last-first||1))*610,y=v=>180-(v-bottom)/(top-bottom)*150;
 let paths=[],segment=[];for(const p of points){if(p.value===null){if(segment.length)paths.push(segment);segment=[]}else segment.push(p)}if(segment.length)paths.push(segment);
 const band=low!==null&&high!==null?`<rect x="60" y="${y(high)}" width="610" height="${Math.max(0,y(low)-y(high))}" fill="var(--surface-selected)"/>`:'';
 return `<figure class="wellness-chart"><figcaption>${esc(label)} <span>${esc(unit)}</span></figcaption><svg viewBox="0 0 720 224" role="img" aria-label="${esc(label)}. Kesin değerler aşağıdaki tabloda.">${band}${[0,.5,1].map(t=>{const v=bottom+(top-bottom)*t;return `<line x1="60" x2="670" y1="${y(v)}" y2="${y(v)}" stroke="var(--line)"/><text x="50" y="${y(v)+4}" text-anchor="end" fill="var(--muted)" font-size="12">${tickfmt(v)}</text>`}).join('')}${paths.map(ps=>`<path d="${ps.map((p,i)=>(i?'L':'M')+x(p)+','+y(p.value)).join(' ')}" fill="none" stroke="var(--accent)" stroke-width="2.5"/>`).join('')}${known.map(p=>`<circle cx="${x(p)}" cy="${y(p.value)}" r="4" fill="var(--accent)"><title>${date(p.date)}: ${labfmt(p.value)} ${esc(unit)}</title></circle>`).join('')}<text x="60" y="210" fill="var(--muted)" font-size="12">${date(points[0].date)}</text><text x="670" y="210" text-anchor="end" fill="var(--muted)" font-size="12">${date(points.at(-1).date)}</text></svg></figure>`;
}
function overview(){
 const s=H.sleepSummary(db(),7),reports=H.reports(db()).valid,latest=reports[0],outside=latest?.rows.filter(r=>['low','high'].includes(H.status(r).code)).length;
 q('health-overview').innerHTML=header('SAĞLIK · KİŞİSEL GÜNLÜĞÜN','Kendini daha yakından tanı.','Uyku, günlük sağlık ve laboratuvar geçmişin. Her ölçüm kendi bağlamında, tek bir yerde.')+`<div class="wellness-grid"><section class="card wellness-feature"><span class="wellness-symbol" aria-hidden="true">☾</span><p class="sports-eyebrow">SON 7 GÜN</p><h3>Dinlenmenin ritmi</h3><p class="wellness-number">${hours(s.average)}</p><p class="hint">${s.count} gecenin ortalama kayıtlı uykusu · ${7-s.count} gün eksik</p><button class="secondary" data-wellness-page="health-sleep">Uyku günlüğünü aç ↗</button></section><section class="card wellness-feature"><span class="wellness-symbol" aria-hidden="true">⌁</span><p class="sports-eyebrow">KAN TAHLİLLERİ</p><h3>Sonuçların zaman içindeki izi</h3><p class="wellness-number">${reports.length}<span> rapor</span></p><p class="hint">${latest?date(latest.date)+' · '+esc(latest.lab)+' · '+outside+' sonuç girilen sınırların dışında':'Laboratuvar raporundaki sonuçları ve referans aralıklarını ekle.'}</p><button class="secondary" data-wellness-page="health-labs">Tahlillerimi aç ↗</button></section></div><section class="card"><div class="wellness-section-title"><div><p class="sports-eyebrow">GÜNLÜK TAKİP</p><h3>Vücudunun verdiği işaretler</h3></div></div><div class="wellness-destinations"><button data-wellness-page="today"><strong>Günlük sağlık durumu</strong><span>Ağrı, yorgunluk ve özbildirimlerin</span><b aria-hidden="true">↗</b></button><button data-wellness-page="reports"><strong>Vücut ve toparlanma</strong><span>3D kas görünümü ve kayıtlı yüklerin</span><b aria-hidden="true">↗</b></button></div></section>`;
 nav(q('health-overview'));
}
function profile(){
 const u=ALOSAccount.user;
 q('account-profile').innerHTML=header('PROFİLİM','Sana ait bir alan.','Hesap bilgilerin, spor profilin ve güvenlik ayarların.')+`<section class="card profile-identity"><div class="profile-monogram" aria-hidden="true">${esc(u.name.trim().slice(0,1).toLocaleUpperCase('tr'))}</div><div><p class="sports-eyebrow">ATHLETE LIFE</p><h3 id="profile-heading-name">${esc(u.name)}</h3><p>@${esc(u.username)}</p></div><button class="secondary" data-wellness-page="character">Spor profilimi düzenle ↗</button></section><div class="wellness-grid profile-columns"><section class="card"><h3>Kişisel bilgiler</h3><p class="hint">Kullanıcı adın giriş kimliğin olarak kalır.</p><form id="profile-details-form" class="wellness-form"><label>Görünen ad<input name="name" autocomplete="name" required maxlength="60" value="${esc(u.name)}"></label><label>E-posta adresi · isteğe bağlı<input name="email" type="email" autocomplete="email" maxlength="254" value="${esc(u.email)}" aria-describedby="profile-email-note"></label><p id="profile-email-note" class="hint">E-posta iletişim bilgisi olarak saklanır; henüz doğrulanmaz. E-postayla giriş veya şifre sıfırlama etkin değildir.</p><button class="primary" type="submit">Bilgilerimi kaydet</button><p id="profile-save-message" role="status"></p></form></section><section id="profile-security" class="card"><h3>Güvenlik</h3><p class="hint">Şifre değişikliği tüm cihazlardaki oturumlarını kapatır. Şifreni unutma durumunda kurtarma kodlarını kullanabilirsin.</p></section></div><section class="card"><div class="wellness-destinations"><button data-wellness-page="settings"><strong>Görünüm ve veriler</strong><span>Açık / koyu tema, hedefler ve yedekleme</span><b aria-hidden="true">↗</b></button></div></section>`;
 let version=u.profileVersion||0;const form=q('profile-details-form');
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button'),msg=q('profile-save-message');button.disabled=true;msg.textContent='Kaydediliyor…';try{const body=Object.fromEntries(new FormData(form));const response=await fetch('/api/auth/profile',{method:'POST',headers:ALOSAccount.headers(),body:JSON.stringify({...body,profileVersion:version})});const result=await response.json();if(!response.ok)throw Error(result.error||'Kaydedilemedi.');ALOSAccount.updateUser(result.user);version=result.user.profileVersion;q('profile-heading-name').textContent=result.user.name;q('account-profile').querySelector('.profile-monogram').textContent=result.user.name.trim().slice(0,1).toLocaleUpperCase('tr');form.elements.name.value=result.user.name;form.elements.email.value=result.user.email;msg.textContent='Bilgilerin hesabına kaydedildi.';AthleteWorkspace.refresh();}catch(error){msg.textContent=error.message}finally{button.disabled=false}};
 // Move existing nodes to preserve the tested password, session flush and recovery handlers.
 const old=document.querySelector('.account-dialog:not([id])'),security=q('profile-security');
 if(old){const details=old.querySelector('details');if(details)security.append(details);const message=old.querySelector('#account-dialog-message');if(message)security.append(message);const recovery=[...old.querySelectorAll('button')].find(b=>b.textContent==='Kurtarma kodlarım');if(recovery)security.append(recovery);const logout=old.querySelector('#account-logout');if(logout)security.append(logout);}
 nav(q('account-profile'));
}
function sleep(){
 q('health-sleep').innerHTML=header('SAĞLIK · UYKU','İyi bir gün, önceki geceden başlar.','Uyanış tarihine göre kaydet. Eksik geceler ortalamaya sıfır olarak eklenmez.')+`<div class="wellness-grid sleep-columns"><section class="card"><h3>Geceyi kaydet</h3><form id="sleep-entry" class="wellness-form"><label>Uyandığın tarih · GG.AA.YYYY<input name="date" placeholder="GG.AA.YYYY" inputmode="numeric" required value="${date(H.today())}"></label><div class="wellness-form-row"><label>Uykuya dalış<input name="sleepTime" type="time" required></label><label>Uyanış<input name="wakeTime" type="time" required></label></div><p class="hint">Uyanış saati daha erkense gece yarısını geçen uyku olarak hesaplanır.</p><label>Gece uyanık kaldığın süre · dk<input name="nightAwake" type="number" min="0" max="1439" step="1" value="0"></label><label>Uyku kaliten<select name="sleepQuality"><option value="">Belirtilmedi</option>${['Çok düşük','Düşük','Orta','İyi','Çok iyi'].map((v,i)=>`<option value="${i+1}">${i+1} · ${v}</option>`).join('')}</select></label><button class="primary">Uykumu kaydet</button><p id="sleep-message" role="status"></p></form></section><section class="card"><div class="wellness-section-title"><h3>Uyku eğilimin</h3><label>Dönem<select id="sleep-range"><option value="7">Son 7 gün</option><option value="30" selected>Son 30 gün</option><option value="90">Son 90 gün</option></select></label></div><div id="sleep-analysis"></div></section></div>`;
 const f=q('sleep-entry');let dirty=false,loaded=null;const sleepSignature=d=>JSON.stringify(['sleepTime','wakeTime','nightAwake','sleepQuality'].map(k=>db().daily?.[d]?.[k]??null));function load(){try{const d=H.date(f.elements.date.value),r=db().daily?.[d]||{};loaded={date:d,signature:sleepSignature(d)};dirty=false;for(const k of ['sleepTime','wakeTime','nightAwake','sleepQuality'])f.elements[k].value=r[k]??(k==='nightAwake'?0:'');q('sleep-message').textContent=H.sleepEntry(r)?'Bu tarihin kaydı açık; kaydettiğinde güncellenir.':''}catch(_){}}
 f.elements.date.onchange=load;f.oninput=()=>{dirty=true};load();window.addEventListener('workspace:navigate',e=>{if(e.detail.page==='health-sleep'&&!dirty)load()});window.EngineBus?.subscribe?.('athlete.state.ready',()=>{if(!dirty)load()},'wellness-sleep-form');
 f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;try{const raw=Object.fromEntries(new FormData(f)),day=H.date(raw.date);if(loaded?.date===day&&loaded.signature!==sleepSignature(day))throw Error('Uyku kaydı başka bir ekranda değişti. Tarihi yeniden seçip son kaydı aç.');const patch=H.saveSleep(db(),raw);q('sleep-message').textContent=await AthleteSports.persist(patch);dirty=false;loaded={date:day,signature:sleepSignature(day)};sleepAnalysis();overview()}catch(err){q('sleep-message').textContent=err.message}finally{b.disabled=false}};
 q('sleep-range').onchange=sleepAnalysis;sleepAnalysis();
}
function sleepAnalysis(){
 if(!q('sleep-analysis'))return;const s=H.sleepSummary(db(),Number(q('sleep-range').value));
 q('sleep-analysis').innerHTML=`<div class="workspace-stats">${metric(hours(s.average),'Ortalama süre')}${metric(s.count+'/'+s.days,'Kayıtlı gece')}${metric(fmt(s.quality)+'/5','Kalite · '+s.rated+' bildirim')}</div>${chart(s.points.map(p=>({date:p.date,value:p.minutes===null?null:p.minutes/60})),{label:'Kayıtlı uyku süresi',unit:'saat'})}<p class="hint">Saatler ve kalite senin bildirimlerin. Bu grafik uyku bozukluğu tanısı koymaz. Boşluklar eksik gecelerdir.</p><details><summary>Gece gece ölçümler</summary><div class="table-wrap"><table><thead><tr><th>Tarih</th><th>Süre</th><th>Kalite</th></tr></thead><tbody>${[...s.points].reverse().map(p=>`<tr><td>${date(p.date)}</td><td>${hours(p.minutes)}</td><td>${fmt(p.quality)}</td></tr>`).join('')}</tbody></table></div></details>`;
}
function labs(){
 const result=H.reports(db(),true),active=result.valid.filter(r=>!r.archivedAt),archived=result.valid.filter(r=>r.archivedAt);
 q('health-labs').innerHTML=header('SAĞLIK · LABORATUVAR GÜNLÜĞÜ','Bir ölçümden, bir geçmişe.','Raporundaki değerleri, birimleri ve referans aralıklarını olduğu gibi kaydet. Dönemler arasındaki değişimi izle.')+`<section class="card wellness-lab-intro"><div><h3>Kan tahlillerim</h3><p class="hint">${active.length} rapor · ${H.library.length} test için kaynaklı açıklama · özel test ekleme</p></div><button id="lab-new" class="primary">＋ Tahlil ekle</button></section><p id="lab-page-message" role="status"></p>${result.invalid?`<p class="wellness-notice">${result.invalid} eski kayıt, gerekli tarih veya ölçüm alanları eksik olduğu için analize alınmadı. Yedekte korunuyor.</p>`:''}<section class="card"><div class="wellness-section-title"><div><p class="sports-eyebrow">DÖNEM KARŞILAŞTIRMASI</p><h3>Değişimin izini sür</h3></div></div><label>Karşılaştırılacak ölçüm<select id="lab-series"><option value="">Test ve ölçüm koşulunu seç</option></select></label><div id="lab-trend"></div></section><section class="card"><h3>Rapor geçmişin</h3><div id="lab-reports">${active.length?active.map(reportCard).join(''):'<div class="wellness-empty"><strong>İlk raporunla başla.</strong><p>Tarih ve laboratuvarı ekle; sonuçları tek raporda biriktir.</p></div>'}</div></section>${archived.length?`<details class="card"><summary>Arşiv · ${archived.length} rapor</summary>${archived.map(reportCard).join('')}</details>`:''}<details class="card wellness-evidence"><summary>Bu analiz nasıl okunmalı? · Kaynaklar ve sınırlar</summary><p>Rapor aralığında olmak hastalık olmadığını, aralık dışında olmak da tek başına hastalık olduğunu göstermez. Belirtiler, yaş, kullanılan ilaçlar ve sağlık öyküsü klinik yorumda gereklidir. Hekimin belirlediği kişisel hedefler rapor aralığından farklı olabilir.</p><p>Bu bölüm rapor takibi ve açıklama sunar; tanı, ilaç/takviye dozu veya tahlilden otomatik antrenman reçetesi üretmez. Laboratuvarın acil/kritik sonuç uyarısı varsa aralık etiketini beklemeden sağlık ekibinin yönlendirmesine uy.</p><p>Trendler yalnız aynı test, birim, laboratuvar, kayıtlı yöntem, açlık durumu ve referans sınırlarında birleştirilir. Bilinmeyen yöntem/açlık bilgisi karşılaştırmayı sınırlar. “&lt;” ve “&gt;” gibi sınırlı sonuçlar kesin sayı olarak grafiğe çizilmez. Birimler otomatik çevrilmez.</p><a href="https://medlineplus.gov/lab-tests/how-to-understand-your-lab-results/" target="_blank" rel="noopener noreferrer">NIH / MedlinePlus: laboratuvar sonuçlarını anlamak</a><p class="hint">Kaynak inceleme tarihi: 16.09.2026. Açıklamalar uygulamayla birlikte saklanır; sağlık kayıtların bu kaynaklara gönderilmez.</p></details>`;
 q('lab-new').onclick=()=>labEditor();
 q('health-labs').querySelectorAll('[data-lab-edit]').forEach(b=>b.onclick=()=>labEditor(result.valid.find(r=>r.id===b.dataset.labEdit)));
 q('health-labs').querySelectorAll('[data-lab-archive]').forEach(b=>b.onclick=async()=>{const old=result.valid.find(r=>r.id===b.dataset.labArchive);b.disabled=true;try{const message=await AthleteSports.persist(H.archive(db(),old.id,!old.archivedAt,JSON.stringify((db().healthLabRecords||[]).find(r=>r.id===old.id))));labs();q('lab-page-message').textContent=message+' '+(old.archivedAt?'Rapor geri alındı.':'Rapor arşive taşındı; aşağıdan geri alabilirsin.');overview()}catch(e){q('lab-page-message').textContent=e.message;b.disabled=false}});
 const groups=H.series(db()),select=q('lab-series');groups.forEach((g,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${g.row.name} · ${g.row.unit} · ${g.lab} · ${fasting(g.fasting)} · ref ${ref(g.row)} · ${g.row.method||'yöntem belirtilmedi'}`;select.append(o)});
 select.onchange=()=>trend(select.value===''?null:groups[Number(select.value)]);if(groups.length)select.value='0';select.onchange();
}
function reportCard(r){
 return `<article class="lab-report"><div class="wellness-section-title"><div><h4>${date(r.date)} <span class="hint">· ${esc(r.lab)}</span></h4><p class="hint">${fasting(r.fasting)} · ${r.rows.length} sonuç · sürüm ${r.revision||1}</p></div><div class="sports-actions">${!r.archivedAt?`<button class="secondary" data-lab-edit="${esc(r.id)}">Düzenle</button>`:''}<button class="secondary" data-lab-archive="${esc(r.id)}">${r.archivedAt?'Geri al':'Arşivle'}</button></div></div><details><summary>Sonuçlar ve açıklamalar</summary><div class="table-wrap"><table><thead><tr><th>Test</th><th>Sonuç</th><th>Rapor aralığı</th><th>Okuma</th></tr></thead><tbody>${r.rows.map(row=>{const s=H.status(row);return `<tr><th>${esc(row.name)}</th><td>${row.comparator==='='?'':esc(row.comparator)}${labfmt(row.value)} ${esc(row.unit)}</td><td>${ref(row)}</td><td><span class="lab-status ${s.code}">${s.label}</span></td></tr>`}).join('')}</tbody></table></div>${r.notes?`<p class="wellness-notes">${esc(r.notes)}</p>`:''}${r.rows.map(row=>{const m=H.library.find(m=>m.id===row.marker);return `<div class="lab-explanation"><strong>${esc(row.name)}</strong><p>${m?esc(m.about)+' '+esc(m.context):'Bu özel test için doğrulanmış açıklama kütüphanesi henüz yok; yalnız rapor sınırları ve aynı ölçümün geçmişi gösterilir.'}</p>${['low','high'].includes(H.status(row).code)?'<p>Girilen rapor sınırının dışında. Sonucu sağlık öykün ve diğer testlerinle birlikte hekiminle değerlendir.</p>':''}${m?`<a href="${m.source}" target="_blank" rel="noopener noreferrer">Kaynak · NIH / MedlinePlus ↗</a>`:''}</div>`}).join('')}<details><summary>Düzenleme geçmişi</summary><ul>${(Array.isArray(db().healthLabHistory)?db().healthLabHistory:[]).filter(h=>h.id===r.id).map(h=>`<li>${esc(h.at)} · ${esc(({create:'Oluşturuldu',edit:'Düzenlendi',archive:'Arşivlendi',restore:'Geri alındı','backup-merge':'Yedekten birleştirildi'})[h.action]||h.action)}${h.before?`<details><summary>Önceki değerler</summary><p>${esc(date(h.before.date))} · ${esc(h.before.lab)}</p><ul>${(h.before.rows||[]).map(row=>`<li>${esc(row.name)}: ${esc(row.comparator)} ${labfmt(row.value)} ${esc(row.unit)} · ref ${ref(row)}</li>`).join('')}</ul></details>`:''}</li>`).join('')}</ul></details></details></article>`;
}
function trend(g){
 const el=q('lab-trend');if(!g){el.innerHTML='<p class="wellness-empty">Kayıt eklediğinde test bazında grafik ve dönem karşılaştırması burada yer alır.</p>';return}
 const points=g.points.map(p=>({...p,value:p.comparator==='='?p.value:null})),exact=points.filter(p=>p.value!==null),delta=exact.length>1&&exact[0].date!==exact.at(-1).date?exact.at(-1).value-exact[0].value:null;
 el.innerHTML=`${chart(points,{label:g.row.name,unit:g.row.unit,low:g.row.low,high:g.row.high})}<div class="workspace-stats">${metric(exact.length,'Kesin ölçüm')}${metric(delta===null?'—':(delta>0?'+':'')+labfmt(delta)+' '+esc(g.row.unit),'İlk / son tarih farkı')}</div><p class="hint">${g.row.low!==null&&g.row.high!==null?'Grafikteki tonlu alan rapor referans aralığıdır. ':''}${delta===null?'Tarihler arası fark için farklı günlerde en az iki kesin ölçüm gerekir.':'Bu fark sayısal değişimdir; tek başına iyileşme veya kötüleşme anlamına gelmez.'} ${g.fasting==='unknown'||!g.row.method?'Açlık durumu veya yöntem bilgisi eksik; ölçüm koşullarının eşitliği doğrulanamadı.':''}</p><details><summary>Kesin değerler ve ölçüm koşulları</summary><p>${esc(g.lab)} · ${fasting(g.fasting)} · ${esc(g.row.method||'Yöntem belirtilmedi')} · referans ${ref(g.row)} ${esc(g.row.unit)}</p><div class="table-wrap"><table><thead><tr><th>Tarih</th><th>Sonuç</th></tr></thead><tbody>${g.points.map(p=>`<tr><td>${date(p.date)}</td><td>${p.comparator==='='?'':esc(p.comparator)}${labfmt(p.value)} ${esc(g.row.unit)}</td></tr>`).join('')}</tbody></table></div></details>`;
}
function labEditor(source=null){
 const expected=source?JSON.stringify((db().healthLabRecords||[]).find(r=>r.id===source.id)):undefined;
 let draft=source?JSON.parse(JSON.stringify(source)):{date:H.today(),lab:'',fasting:'unknown',notes:'',rows:[{marker:'',unit:'',value:'',low:'',high:'',comparator:'=',method:''}]};
 const modal=AthleteSports.dialog('health-lab-editor',source?'Tahlili düzenle':'Tahlil ekle'),content=modal.querySelector('.sports-content'),message=modal.querySelector('.sports-message');
 let busy=false;
 modal.querySelector('.sports-eyebrow').textContent='ATHLETE LIFE · SAĞLIK';
 function collect(){const f=q('lab-editor-form');for(const k of ['date','lab','fasting','notes'])draft[k]=f.elements[k].value;draft.rows=[...f.querySelectorAll('[data-lab-row]')].map(el=>Object.fromEntries([...el.querySelectorAll('[data-field]')].map(x=>[x.dataset.field,x.value])))}
 function draw(){
 content.innerHTML=`<form id="lab-editor-form" class="wellness-form"><div class="wellness-form-row"><label>Örnek alınan tarih · GG.AA.YYYY<input name="date" placeholder="GG.AA.YYYY" inputmode="numeric" required value="${esc(date(draft.date))}"></label><label>Laboratuvar / hastane<input name="lab" required maxlength="100" placeholder="Raporundaki kurum adı" value="${esc(draft.lab)}"></label></div><label>Örnek alım koşulu<select name="fasting">${[['unknown','Belirtilmedi'],['fasting','Açlık'],['nonfasting','Tokluk']].map(([v,l])=>`<option value="${v}" ${draft.fasting===v?'selected':''}>${l}</option>`).join('')}</select></label><p class="hint">Sonucu ve birimi raporundan aynen gir. Referans sınırını bilmiyorsan boş bırak; uygulama evrensel bir normal aralık varsaymaz.</p><div id="lab-editor-rows">${draft.rows.map((r,i)=>`<fieldset data-lab-row="${i}"><legend>Sonuç ${i+1}</legend><label>Test<select data-field="marker" required><option value="">Test seç</option>${H.library.map(m=>`<option value="${m.id}" ${m.id===r.marker?'selected':''}>${m.name}</option>`).join('')}<option value="custom" ${r.marker==='custom'?'selected':''}>Başka bir test</option></select></label><label ${r.marker==='custom'?'':'hidden'}>Test adı<input data-field="name" maxlength="100" value="${esc(r.name)}" ${r.marker==='custom'?'required':''}></label><div class="wellness-measurement"><label>İşaret<select data-field="comparator">${['=','<','>','≤','≥'].map(c=>`<option value="${esc(c)}" ${c===(r.comparator||'=')?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Sonuç<input data-field="value" inputmode="decimal" required value="${esc(r.value)}" placeholder="Örn. 42,5"></label><label>Birim<input data-field="unit" list="lab-units-${i}" required maxlength="40" value="${esc(r.unit)}" placeholder="Rapordaki birim"><datalist id="lab-units-${i}">${(H.library.find(m=>m.id===r.marker)?.units||[]).map(u=>`<option value="${esc(u)}">`).join('')}</datalist></label></div><div class="wellness-form-row"><label>Referans alt sınırı<input data-field="low" inputmode="decimal" value="${esc(r.low)}" placeholder="İsteğe bağlı"></label><label>Referans üst sınırı<input data-field="high" inputmode="decimal" value="${esc(r.high)}" placeholder="İsteğe bağlı"></label></div><label>Ölçüm yöntemi · raporda varsa<input data-field="method" maxlength="100" value="${esc(r.method)}" placeholder="İsteğe bağlı"></label>${draft.rows.length>1?`<button class="secondary" type="button" data-lab-remove="${i}">Bu satırı kaldır</button>`:''}</fieldset>`).join('')}</div><button class="secondary" id="lab-add-row" type="button">＋ Başka sonuç ekle</button><label>Rapor notu · isteğe bağlı<textarea name="notes" maxlength="2000" placeholder="Örnek alımı, yakın tarihli yoğun egzersiz, hekim notu…">${esc(draft.notes)}</textarea></label><button class="primary" type="submit">Raporu kaydet</button></form>`;
 content.querySelectorAll('[data-field="marker"]').forEach(sel=>sel.onchange=()=>{collect();const i=+sel.closest('[data-lab-row]').dataset.labRow;draft.rows[i]={marker:sel.value,unit:'',value:'',low:'',high:'',comparator:'=',method:'',name:''};draw();q('lab-editor-rows').querySelectorAll('[data-field="value"]')[i].focus()});
 q('lab-add-row').onclick=()=>{collect();if(draft.rows.length>=60){message.textContent='Bir raporda en fazla 60 sonuç olabilir.';return}draft.rows.push({marker:'',unit:'',value:'',low:'',high:'',comparator:'=',method:''});draw();content.querySelector('[data-lab-row]:last-child select').focus()};
 content.querySelectorAll('[data-lab-remove]').forEach(b=>b.onclick=()=>{collect();draft.rows.splice(+b.dataset.labRemove,1);draw()});
 q('lab-editor-form').onsubmit=async e=>{e.preventDefault();if(busy)return;collect();const b=e.currentTarget.querySelector('[type="submit"]');try{const patch=H.saveReport(db(),draft,{id:source?.id,expected});busy=true;b.disabled=true;const result=await AthleteSports.persist(patch);modal.close();labs();q('lab-page-message').textContent=result;overview()}catch(err){message.textContent=err.message}finally{busy=false;b.disabled=false}};
 }
 draw();modal.showModal();
}
const icons={today:'M3 11 12 3l9 8M5 10v10h5v-6h4v6h5V10',training:'M4 7v10M7 5v14M7 12h10M17 5v14M20 7v10',nutrition:'M6 3v6c0 4 6 4 6 0V3M9 3v18M19 3c-4 4-4 9 0 9V3m0 9v9',health:'M12 20S3 14 3 8c0-5 7-6 9-1 2-5 9-4 9 1 0 6-9 12-9 12Z',growth:'M4 4v16h16M7 15l4-5 4 2 5-7',profile:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2'};
function init(){
 document.body.classList.add('premium-workspace');document.querySelector('.topbar').id='premium-topbar';const brand=document.querySelector('.brand h1');if(brand)brand.textContent='Athlete Life';const tagline=document.querySelector('.brand p');if(tagline)tagline.textContent='Antrenman. Sağlık. Gelişim.';const main=document.querySelector('main.main');
 for(const id of ['health-overview','health-sleep','health-labs','account-profile']){const section=document.createElement('section');section.className='page';section.id=id;main.append(section)}
 document.querySelectorAll('[data-workspace-group]').forEach(b=>{const path=icons[b.dataset.workspaceGroup];if(path)b.insertAdjacentHTML('afterbegin',`<svg viewBox="0 0 24 24" width="21" height="21" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${path}"/></svg>`)});
 for(const id of ['bedTime','sleepTime','wakeTime','nightAwake','sleepQuality'])q(id)?.closest('label')?.setAttribute('hidden','');
 const daily=q('sleepTime')?.closest('.form-grid');if(daily){const link=document.createElement('button');link.type='button';link.className='secondary';link.textContent='Uyku kaydı ve analizini aç ↗';link.onclick=()=>AthleteWorkspace.navigate('health-sleep');daily.before(link)}
 const recovery=q('detail-recovery');if(recovery)recovery.classList.add('design-duplicate');
 document.querySelector('[data-detail="detail-recovery"]')?.classList.add('design-duplicate');
 profile();sleep();labs();overview();
 window.addEventListener('workspace:navigate',e=>{if(e.detail.page==='health-overview')overview();if(e.detail.page==='health-labs')labs();if(e.detail.page==='health-sleep')sleepAnalysis()});
 window.EngineBus?.subscribe?.('athlete.state.ready',()=>{overview();labs();sleepAnalysis()},'wellness-state');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
