import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync,mkdirSync} from 'node:fs';
import AxeBuilder from '../../apps/web/node_modules/@axe-core/playwright/dist/index.mjs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10011',name='alos_test_sport_browser_'+Date.now(),out=root+'/docs/evidence/account-chat';let server,browser,page,created=false;const errors=[];
try{
 try{await fetch(base+'/health/ready');throw Error('Test port occupied');}catch(e){if(e.message==='Test port occupied')throw e;}
 mkdirSync(out,{recursive:true});execFileSync(python,['tools/v2/test_database.py','create',name],{stdio:'pipe'});created=true;
 server=spawn(python,['-m','uvicorn','tools.v2.account_chat_fixture:create','--factory','--host','127.0.0.1','--port','10011','--no-access-log'],{env:{...process.env,PYTHONPATH:root+'/apps/api:'+root,PYTHON_DOTENV_DISABLED:'1',STORAGE_BACKEND:'sqlite',ACCOUNT_STORAGE_BACKEND:'sqlite',ALOS_SYNTHETIC_SPORT_DB:name},stdio:'ignore'});
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByRole('button',{name:'Hesap oluştur',exact:true}).click();
 await page.getByLabel('Adın',{exact:true}).fill('Sentetik Yeni Kişi');await page.getByLabel('E-posta adresin',{exact:true}).fill('new@example.org');await page.getByLabel('Kullanıcı adı',{exact:true}).fill('syntheticnew');await page.getByLabel('Şifre',{exact:true}).fill('synthetic-password-123');
 await page.getByRole('button',{name:'Doğrulama kodu gönder',exact:true}).click();await expect(page.getByLabel('E-postana gelen 6 haneli kod',{exact:true})).toBeVisible();await page.screenshot({path:out+'/email-code.png',fullPage:true});
 await page.getByLabel('E-postana gelen 6 haneli kod',{exact:true}).fill('000000');await page.getByRole('button',{name:'Kodu doğrula ve hesap oluştur',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Kod yanlış');
 await page.getByLabel('E-postana gelen 6 haneli kod',{exact:true}).fill('123456');await page.getByRole('button',{name:'Kodu doğrula ve hesap oluştur',exact:true}).click();await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible({timeout:20000});
 await page.goto(base+'/#tools');await page.getByRole('link',{name:/AI ile sohbet et/}).click();await expect(page.getByRole('heading',{name:'AI ile sohbet et',exact:true})).toBeVisible();
 await page.getByLabel('Mesajın',{exact:true}).fill('Bu spor ekipmanını yorumlar mısın?');await expect(page.getByRole('button',{name:'Gönder',exact:true})).toBeDisabled();
 const png=execFileSync(python,['-c','from PIL import Image;import io,sys;f=io.BytesIO();Image.new("RGB",(12,12),(100,120,150)).save(f,format="PNG");sys.stdout.buffer.write(f.getvalue())']);
 await page.getByLabel('Görsel ekle (isteğe bağlı)',{exact:true}).setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:png});await expect(page.getByAltText('Gönderilecek görsel')).toBeVisible();await page.getByRole('checkbox',{name:/Mesajlarımın ve seçtiğim görselin EVREN/}).check();
 await page.getByRole('button',{name:'Gönder',exact:true}).click();await expect(page.locator('.chat-message.assistant')).toContainText('Sentetik spor yanıtı');await expect(page.locator('.chat-message.user img')).toBeVisible();
 for(const width of [390,1280]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).include('.ai-chat').analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);await page.screenshot({path:out+`/chat-${width}.png`,fullPage:true});}
 await page.reload();await expect(page.locator('.chat-message')).toHaveCount(0);
 await page.goto(base+'/#profile');await page.getByRole('button',{name:'Hesabı kalıcı olarak sil',exact:true}).click();await page.getByLabel('Silmek için mevcut şifrem',{exact:true}).fill('synthetic-password-123');await page.getByRole('checkbox',{name:'Hesabımı kalıcı silmek istiyorum.',exact:true}).check();await page.screenshot({path:out+'/delete-confirm.png',fullPage:true});await page.getByRole('button',{name:'Hesabımı kalıcı sil',exact:true}).click();await expect(page.getByRole('button',{name:'Giriş yap',exact:true})).toBeVisible({timeout:15000});
 await page.getByLabel('Kullanıcı adı',{exact:true}).fill('syntheticnew');await page.getByLabel('Şifre',{exact:true}).fill('synthetic-password-123');await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Kullanıcı adı veya şifre yanlış');
 expect(errors).toEqual([]);writeFileSync(out+'/browser-results.json',JSON.stringify({result:'PASS',errors,checks:['Code before registration; wrong then correct code','Chat consent and image upload; mobile/desktop Axe','Ephemeral chat cleared on reload','Profile deletion and rejected login afterward'],transport:'synthetic email and EVREN',browser:browser.version()},null,2));console.log('Account/chat browser PASS');
}catch(e){if(page)await page.screenshot({path:out+'/failure.png',fullPage:true});throw e;}finally{if(browser)await browser.close();if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r));}if(created)execFileSync(python,['tools/v2/test_database.py','drop',name],{stdio:'pipe'});}
