import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync,mkdirSync} from 'node:fs';
import AxeBuilder from '../../apps/web/node_modules/@axe-core/playwright/dist/index.mjs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10011',name='alos_test_sport_browser_'+Date.now(),out=root+'/docs/evidence/admin';let server,browser,page,created=false;const errors=[];
try{
 try{await fetch(base+'/health/ready');throw Error('Test port occupied');}catch(e){if(e.message==='Test port occupied')throw e;}
 mkdirSync(out,{recursive:true});execFileSync(python,['tools/v2/test_database.py','create',name],{stdio:'pipe'});created=true;
 server=spawn(python,['-m','uvicorn','tools.v2.admin_fixture:create','--factory','--host','127.0.0.1','--port','10011','--no-access-log'],{env:{...process.env,PYTHONPATH:root+'/apps/api:'+root,PYTHON_DOTENV_DISABLED:'1',STORAGE_BACKEND:'sqlite',ACCOUNT_STORAGE_BACKEND:'sqlite',ALOS_SYNTHETIC_SPORT_DB:name},stdio:'ignore'});
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill('deniz');await page.getByLabel('Şifre',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await expect(page.getByRole('heading',{name:'Yönetici paneli',exact:true})).toBeVisible();await expect(page.getByRole('navigation',{name:'Mobil ana gezinme',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:/Arda Test · @arda/}).click();await expect(page.getByRole('heading',{name:'Kullanıcı kayıtları',exact:true})).toBeVisible();
 for(const width of [390,1280]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).include('.admin-shell').analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);await page.screenshot({path:out+`/panel-${width}.png`,fullPage:true});}
 await page.getByText('Hesabı yönet',{exact:true}).click();await page.getByLabel('İşlem',{exact:true}).selectOption('delete');await page.getByLabel('Hedef kullanıcı adını yaz',{exact:true}).fill('arda');await page.getByLabel('Yönetici şifren',{exact:true}).fill('wrong-password');await page.getByRole('checkbox',{name:'Seçtiğim işlemi bu kullanıcı için onaylıyorum.',exact:true}).check();await page.getByRole('button',{name:'İşlemi uygula',exact:true}).click();await expect(page.getByRole('alert')).toContainText('şifreni kontrol et');
 await page.getByLabel('Yönetici şifren',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'İşlemi uygula',exact:true}).click();await expect(page.getByRole('status')).toContainText('kalıcı silindi');await expect(page.getByRole('button',{name:/Arda Test · @arda/})).toHaveCount(0);
 await page.getByRole('button',{name:'Son işlemleri göster',exact:true}).click();await expect(page.getByText(/admin_delete:/)).toBeVisible();await page.getByRole('button',{name:/Deniz Test · @deniz/}).click();await expect(page.getByText('Hesabı yönet',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Çıkış',exact:true}).click();await expect(page.getByRole('button',{name:'Giriş yap',exact:true})).toBeVisible();
 expect(errors).toEqual([]);writeFileSync(out+'/browser-results.json',JSON.stringify({result:'PASS',errors,checks:['Admin-only layout','User detail and records','Wrong administrator password rejected','Confirmed target deletion','Audit visible and admin self-delete absent','Mobile/desktop Axe and overflow'],environment:'synthetic'},null,2));console.log('Admin browser PASS');
}catch(e){if(page)await page.screenshot({path:out+'/failure.png',fullPage:true});throw e;}finally{if(browser)await browser.close();if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r));}if(created)execFileSync(python,['tools/v2/test_database.py','drop',name],{stdio:'pipe'});}
