import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import AxeBuilder from '../../apps/web/node_modules/@axe-core/playwright/dist/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {mkdirSync,writeFileSync} from 'node:fs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',port=10005,base='http://127.0.0.1:'+port;
const dbName='alos_test_browser_'+Date.now();
const env={...process.env,PYTHONPATH:root+'/apps/api',ALOS_V2_ENABLED:'1',ALOS_V2_ENVIRONMENT:'test',ALOS_V2_DATABASE_URL:process.env.ALOS_TEST_BACKEND==='mongodb'?'mongodb://127.0.0.1:27028/?replicaSet=alos-test':'postgresql://localhost:15432/'+dbName,ALOS_V2_MONGO_DATABASE:dbName,ALOS_V2_PUBLIC_ORIGIN:base};
const evidence=root+'/docs/evidence/stage-1';mkdirSync(evidence,{recursive:true});
let server,browser;const errors=[];const results=[];
function start(){server=spawn(python,['-m','uvicorn','alos.main:create_app','--factory','--host','127.0.0.1','--port',String(port),'--no-access-log'],{cwd:root,env,stdio:['ignore','pipe','pipe']});server.stderr.on('data',()=>{});}
async function ready(){for(let i=0;i<80;i++){try{if((await fetch(base+'/health/ready')).ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('Server not ready')}
async function stop(){if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r));server=null}}
async function login(context,username='deniz',password='test-password-123'){const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill(username);await page.getByLabel('Şifre',{exact:true}).fill(password);await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await expect(page.getByRole('heading',{name:'Merhaba, '+(username==='deniz'?'Deniz':'Arda')+'.'})).toBeVisible();await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible();return page}
async function boot(page){return page.evaluate(async()=>{const r=await fetch('/api/v2/bootstrap');if(!r.ok)throw Error(r.status);return r.json()})}
async function week(page){await page.goto(base+'/?date=2026-09-15#week');await expect(page.getByRole('heading',{name:'Haftam',exact:true})).toBeVisible();return page.locator('.shift-day').filter({has:page.getByRole('heading',{name:'15 Eylül Salı',exact:true})})}
async function synced(page){await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible({timeout:20000})}
try{
 execFileSync(python,['tools/v2/test_database.py','create',dbName],{cwd:root});start();await ready();
 browser=await chromium.launch({executablePath:process.env.ALOS_BROWSER_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 const a=await browser.newContext({viewport:{width:1360,height:980}});const pa=await login(a);let day=await week(pa);
 await day.getByLabel('Gün türü').selectOption('work');await day.getByLabel('Başlangıç').fill('14:00');await day.getByLabel('Bitiş').fill('22:00');await day.getByRole('button',{name:'Değişiklikleri kaydet'}).click();await synced(pa);
 await pa.getByRole('button',{name:'Haftayı değerlendir'}).click();await expect(pa.getByRole('heading',{name:'Zaman önerisi',exact:true})).toBeVisible();await synced(pa);await pa.getByRole('button',{name:'Bu öneriyi onayla'}).click();await expect(pa.getByRole('heading',{name:'Onayladığın plan'})).toBeVisible();await synced(pa);
 const baseline=await boot(pa);expect(baseline.shifts[0].start_local).toBe('14:00');expect(baseline.optimizations[0].status).toBe('accepted');await pa.screenshot({path:evidence+'/week-desktop.png',fullPage:true});
 const b=await browser.newContext();const pb=await login(b);expect((await boot(pb)).shifts).toEqual(baseline.shifts);results.push('P-01/P-02 second independent context: PASS');
 await stop();start();await ready();const fresh=await browser.newContext();const pf=await login(fresh);const restarted=await boot(pf);expect(restarted.shifts).toEqual(baseline.shifts);expect(restarted.optimizations).toEqual(baseline.optimizations);await fresh.close();results.push('P-01/P-02 SIGKILL server, empty browser storage, new login: PASS');
 await a.setOffline(true);await day.getByLabel('Sosyal plan / not').fill('Çevrimdışı not');await day.getByRole('button',{name:'Değişiklikleri kaydet'}).click();await expect(pa.getByRole('button',{name:'1 kayıt eşitlenmeyi bekliyor'})).toBeVisible();const queue=await pa.evaluate(async()=>{const list=await indexedDB.databases();const name=list.find(x=>x.name.startsWith('alos-v2:')).name;return new Promise(resolve=>{const r=indexedDB.open(name);r.onsuccess=()=>{const q=r.result.transaction('outbox').objectStore('outbox').getAll();q.onsuccess=()=>resolve(q.result)}})});expect(queue.length).toBe(1);const op=queue[0].id;
 await pa.close();await a.setOffline(false);const reopened=await a.newPage();await reopened.goto(base+'/?date=2026-09-15#week');await synced(reopened);await expect.poll(async()=> (await boot(reopened)).shifts[0].social,{timeout:20000}).toBe('Çevrimdışı not');expect((await boot(reopened)).shifts[0].version).toBe(2);results.push('P-09 offline IDB queue, tab closes, reconnect one effect: PASS '+op);
 // Deliberately lose the ACK after the real server has committed.
 let lost=false;await reopened.route('**/api/v2/commands',async route=>{if(!lost){lost=true;await route.fetch();await route.abort('connectionfailed')}else await route.continue()});day=await week(reopened);await day.getByLabel('Sosyal plan / not').fill('Yanıtı kaybolan kayıt');await day.getByRole('button',{name:'Değişiklikleri kaydet'}).click();await expect.poll(async()=> (await boot(pb)).shifts[0].social,{timeout:15000}).toBe('Yanıtı kaybolan kayıt');await synced(reopened);expect((await boot(reopened)).shifts[0].version).toBe(3);await reopened.unroute('**/api/v2/commands');results.push('P-05 lost ACK retried without duplicate version: PASS');
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const pm=await login(mobile);await pm.screenshot({path:evidence+'/today-mobile.png',fullPage:true});expect(await pm.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page:pm}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();writeFileSync(evidence+'/axe-mobile.json',JSON.stringify(axe.violations,null,2));expect(axe.violations).toEqual([]);results.push('mobile 390×844 overflow + axe WCAG: PASS');
 const other=await browser.newContext();const po=await login(other,'arda','test-password-456');expect((await boot(po)).shifts).toEqual([]);results.push('second account empty and isolated: PASS');
 expect(errors).toEqual([]);writeFileSync(evidence+'/browser-results.json',JSON.stringify({results,pageErrors:errors,browser:browser.version(),viewport:[1360,980,390,844]},null,2));
 console.log(results.join('\n'));
}catch(e){writeFileSync(evidence+'/browser-failure.txt',String(e.stack));throw e}finally{if(browser)await browser.close();await stop();execFileSync(python,['tools/v2/test_database.py','drop',dbName],{cwd:root})}
