import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync,mkdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import AxeBuilder from '../../apps/web/node_modules/@axe-core/playwright/dist/index.mjs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10010',name='alos_test_catalog_progress_'+Date.now();let server,browser,page;const errors=[],checks=[];
async function api(path,body){return page.evaluate(async({path,body})=>{const me=await(await fetch('/api/v2/auth/me')).json();const r=await fetch('/api/v2/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':me.csrf},body:JSON.stringify(body)}:{});if(!r.ok)throw Error(await r.text());return r.json()},{path,body});}
async function command(type,payload){return api('commands',{operation_id:randomUUID(),entity_id:randomUUID(),expected_version:0,schema_version:1,command_type:type,payload});}
async function synced(){await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible({timeout:20000});}
try{
 try{await fetch(base+'/health/ready');throw Error('Test port occupied');}catch(e){if(e.message==='Test port occupied')throw e;}
 mkdirSync(root+'/docs/evidence/catalog-progress',{recursive:true});execFileSync(python,['tools/v2/test_database.py','create',name],{stdio:'pipe'});
 server=spawn(python,['-m','uvicorn','alos.main:create_app','--factory','--host','127.0.0.1','--port','10010','--no-access-log'],{env:{...process.env,PYTHONPATH:root+'/apps/api',ALOS_V2_ENABLED:'1',ALOS_V2_ENVIRONMENT:'test',ALOS_V2_PUBLIC_ORIGIN:base,ALOS_V2_DATABASE_URL:'postgresql://localhost:15432/'+name},stdio:'ignore'});
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill('deniz');await page.getByLabel('Şifre',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await synced();
 await page.getByRole('button',{name:'Devam',exact:true}).click();const sports=page.getByLabel('Çalıştığın branşı ekle',{exact:true});await expect(sports.locator('option')).toHaveCount(200);await expect(sports.locator('optgroup')).toHaveCount(15);
 await page.getByLabel('Branş kategorisi',{exact:true}).selectOption('Dövüş sporları');await expect(sports.locator('option')).toHaveCount(18);await sports.selectOption('boxing');await page.getByLabel('Branş kategorisi',{exact:true}).selectOption('Yüzme ve su sporları');await sports.selectOption('swimming');await page.getByRole('button',{name:'Devam',exact:true}).click();
 await page.locator('summary').filter({hasText:'Boks · branşa özgü deneyimim'}).click();await page.getByLabel('boxing seviyesi',{exact:true}).selectOption('new');await page.getByLabel('boxing Şu an haftada kaç seans?',{exact:true}).fill('2');
 await page.locator('summary').filter({hasText:'Havuz yüzmesi · branşa özgü deneyimim'}).click();await page.getByLabel('swimming seviyesi',{exact:true}).selectOption('advanced');await page.getByLabel('swimming Kaç yıldır yapıyorsun?',{exact:true}).fill('5');await page.reload();await synced();await page.locator('summary').filter({hasText:'Havuz yüzmesi · branşa özgü deneyimim'}).click();await expect(page.getByLabel('swimming seviyesi',{exact:true})).toHaveValue('advanced');checks.push('199 sports grouped into 15 categories; independent sport experience persists');
 await page.goto(base+'/#workout');await synced();await page.locator('summary').filter({hasText:'Hareket kütüphanesi'}).click();const catalog=await api('catalogs');await expect(page.getByLabel('İncelemek istediğin hareket',{exact:true}).locator('option')).toHaveCount(catalog.movements.length);expect(catalog.movements.length).toBeGreaterThan(6);
 await page.getByLabel('Hareket kütüphanesinde ara',{exact:true}).fill('Halkada L tutuş');await expect(page.getByRole('heading',{name:'Halkada L tutuş',exact:true})).toBeVisible();await expect(page.getByRole('img',{name:/Katalog kas bölgeleri:/})).toBeVisible();await page.screenshot({path:root+'/docs/evidence/catalog-progress/catalog-mobile.png',fullPage:true});checks.push('complete canonical catalog, Turkish search and muscle schematic');
 const opened=await command('session.open',{local_date:'2026-09-15',title:'Private synthetic session'});await command('set.save',{session_id:opened.entity.id,movement_id:'ring-l-sit',name:'Private synthetic label',modality:'isometric',seconds:12,time_precision:'date_only'});await command('measurement.save',{local_date:'2026-09-15',metric:'weight',value:72,unit:'kg',protocol:'synthetic'});
 let preview,calls=0;
 await page.route('**/api/v2/ai-progress-preview',async route=>{const response=await route.fetch();preview=await response.json();preview.configuration={available:true,provider:'EVREN',model:'synthetic-model',consent_version:'progress-evren-v1',message:'Sentetik sağlayıcı'};await route.fulfill({json:preview});});
 await page.route('**/api/v2/ai-progress-review',async route=>{calls++;const body=route.request().postDataJSON();expect(body.preview_digest).toBe(preview.digest);expect(body.consent).toBe('progress-evren-v1');await route.fulfill({json:{context:preview.context,digest:preview.digest,provider:'EVREN',model:'synthetic-model',version:'ai-progress-1',review:{overview:'Sentetik dönem değerlendirmesi.',findings:[{title:'Kayıt düzeni',text:'Kas büyümesi ölçümü değil; kayıt özeti.',evidence_ids:[preview.context.facts[0].id]}],next_steps:['Karşılaştırılabilir kayıt tut.'],limitations:['Sınırlı kayıt.']}}});});
 await page.goto(base+'/?date=2026-09-15#status');await synced();await page.locator('summary').filter({hasText:'AI ile dönem değerlendirmesi'}).click();await page.getByLabel('İncelenecek dönem',{exact:true}).selectOption('14');await page.getByRole('button',{name:'Gönderilecek verileri incele',exact:true}).click();const analyze=page.getByRole('button',{name:'Gelişimimi AI ile analiz et',exact:true});await expect(analyze).toBeDisabled();expect(calls).toBe(0);
 await page.getByRole('checkbox',{name:/Bu özetteki seçili kayıtlarımın EVREN/}).check();await page.getByRole('checkbox',{name:'Kilo, bel çevresi ve vücut ölçülerim',exact:true}).check();await expect(analyze).toHaveCount(0);await page.getByRole('button',{name:'Gönderilecek verileri incele',exact:true}).click();await expect(analyze).toBeDisabled();await page.getByRole('checkbox',{name:/Bu özetteki seçili kayıtlarımın EVREN/}).check();await analyze.click();await expect(page.getByRole('article',{name:'AI gelişim yorumu'})).toContainText('Sentetik dönem değerlendirmesi');expect(calls).toBe(1);expect(preview.context.facts.some(f=>f.kind==='body_measurement')).toBe(true);expect(JSON.stringify(preview.context)).not.toContain('Private synthetic');checks.push('preview before consent; scope change invalidates consent; grounded period review renders; identity excluded');
 for(const width of [390,1280]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).include('.ai-progress').analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);await page.screenshot({path:root+`/docs/evidence/catalog-progress/review-${width}.png`,fullPage:true});}
 expect(errors).toEqual([]);writeFileSync(root+'/docs/evidence/catalog-progress/results.json',JSON.stringify({result:'PASS',checks,errors,browser:browser.version()},null,2));console.log('Catalog, categorized sports and AI progress browser: PASS');
}catch(e){if(page){await page.screenshot({path:root+'/docs/evidence/catalog-progress/failure.png',fullPage:true});console.error(await page.locator('body').innerText());}throw e;}finally{if(browser)await browser.close();if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r));}execFileSync(python,['tools/v2/test_database.py','drop',name],{stdio:'pipe'});}
