import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10005',name='alos_test_lifestyle_'+Date.now();let server,browser,page;const errors=[];
async function api(path,body){return page.evaluate(async({path,body})=>{const me=await(await fetch('/api/v2/auth/me')).json();const r=await fetch('/api/v2/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':me.csrf},body:JSON.stringify(body)}:{});if(!r.ok)throw Error(await r.text());return r.json()},{path,body})}
async function synced(){await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible({timeout:20000})}
try{
 execFileSync(python,['tools/v2/test_database.py','create',name],{cwd:root});server=spawn(python,['-m','uvicorn','alos.main:create_app','--factory','--host','127.0.0.1','--port','10005','--no-access-log'],{cwd:root,env:{...process.env,PYTHONPATH:root+'/apps/api',ALOS_V2_ENABLED:'1',ALOS_V2_ENVIRONMENT:'test',ALOS_V2_PUBLIC_ORIGIN:base,ALOS_V2_DATABASE_URL:process.env.ALOS_TEST_BACKEND==='mongodb'?'mongodb://127.0.0.1:27028/?replicaSet=alos-test':'postgresql://localhost:15432/'+name,ALOS_V2_MONGO_DATABASE:name},stdio:'ignore'});for(let i=0;i<80;i++){try{if((await fetch(base+'/health/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({executablePath:process.env.ALOS_BROWSER_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill('deniz');await page.getByLabel('Şifre',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await synced();

 await page.goto(base+'/?date=2026-09-15#nutrition');await page.getByRole('button',{name:'Besinler ve tarifler',exact:true}).click();let section=page.locator('section').filter({has:page.getByRole('heading',{name:'Besin kütüphanem',exact:true})});await section.getByRole('button',{name:'Ekle',exact:true}).click();await page.getByLabel('Besin adı',{exact:true}).fill('Synthetic oats');for(const [label,value] of [['Enerji (kcal)','400'],['Protein (g)','12,5'],['Karbonhidrat (g)','60'],['Yağ (g)','8']])await page.getByLabel(label,{exact:true}).fill(value);await page.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).foods.length).toBe(1);
 await page.getByRole('button',{name:'Günüm',exact:true}).click();section=page.locator('section').filter({has:page.getByRole('heading',{name:'Öğünler',exact:true})});await section.getByRole('button',{name:'Ekle',exact:true}).click();await page.getByLabel('Öğün adı',{exact:true}).fill('Breakfast');await page.getByLabel('Tüketilen miktar (g)',{exact:true}).fill('50');await page.getByLabel('Kütüphaneden besin',{exact:true}).selectOption({label:'Synthetic oats'});await page.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).meals[0]?.protein_g).toBe(6.25);
 section=page.locator('section').filter({has:page.getByRole('heading',{name:'Su',exact:true})});await section.getByRole('button',{name:'Ekle',exact:true}).click();await page.getByLabel('Su (ml)',{exact:true}).fill('250');await page.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).hydrations.length).toBe(1);
 await page.goto(base+'/?date=2026-09-15#health');section=page.locator('section').filter({has:page.getByRole('heading',{name:'Nasıl hissediyorum?',exact:true})});await section.getByRole('button',{name:'Ekle',exact:true}).click();await page.getByLabel('Enerji (0–10)',{exact:true}).fill('7');await page.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).checkins[0]?.energy).toBe(7);
 section=page.locator('section').filter({has:page.getByRole('heading',{name:'Uyku geceleri',exact:true})});await section.getByRole('button',{name:'Ekle',exact:true}).click();await page.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).sleeps.length).toBe(1);
 await page.goto(base+'/?date=2026-09-15#capability');await page.getByLabel('Ölçmek istediğim test',{exact:true}).selectOption('front_lever');await page.getByRole('button',{name:'Ekle',exact:true}).click();await page.getByLabel('Ölçülen sonuç',{exact:true}).fill('12,5');await page.getByLabel('Varyasyon / koşul',{exact:true}).fill('tuck');await page.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).capabilitys.length).toBe(1);
 await page.reload();await synced();await page.getByLabel('Ölçmek istediğim test',{exact:true}).selectOption('front_lever');await expect(page.getByText('12,5 seconds · tuck',{exact:true})).toBeVisible();
 await page.getByLabel('Yetenek alanı',{exact:true}).selectOption('custom');await page.getByLabel('Kendi testimin adı',{exact:true}).fill('Sentetik denge testi');await page.getByRole('button',{name:'Bu testin sonucunu gir',exact:true}).click();await page.getByRole('button',{name:'Ekle',exact:true}).click();await page.getByLabel('Ölçülen sonuç',{exact:true}).fill('24,5');await page.getByLabel('Birim',{exact:true}).selectOption('seconds');await page.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).capabilitys.length).toBe(2);await page.reload();await synced();await page.getByLabel('Yetenek alanı',{exact:true}).selectOption('custom');await page.getByLabel('Ölçmek istediğim test',{exact:true}).selectOption('custom:Sentetik denge testi');await expect(page.getByText('24,5 seconds · standard',{exact:true})).toBeVisible();
 const second=await browser.newContext();const secondPage=await second.newPage();await secondPage.goto(base);await secondPage.getByLabel('Kullanıcı adı',{exact:true}).fill('deniz');await secondPage.getByLabel('Şifre',{exact:true}).fill('test-password-123');await secondPage.getByRole('button',{name:'Giriş yap',exact:true}).click();await expect(secondPage.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible();await secondPage.goto(base+'/?date=2026-09-15#nutrition');await expect(secondPage.getByText('Breakfast',{exact:true})).toBeVisible();await expect(secondPage.getByText('250 ml',{exact:true})).toBeVisible();
 const snapshot=await api('bootstrap');expect(snapshot.meals[0].grams).toBe(50);expect(snapshot.sleeps[0].start_at).toBe('2026-09-14T20:00:00+00:00');expect(errors).toEqual([]);await page.screenshot({path:root+'/docs/evidence/stage-4/capability-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.goto(base+'/?date=2026-09-15#nutrition');await page.screenshot({path:root+'/docs/evidence/stage-4/nutrition-mobile.png',fullPage:true});
 writeFileSync(root+'/docs/evidence/stage-4/browser-results.json',JSON.stringify({result:'PASS',browser:browser.version(),viewport:[390,844],journey:'Food library → comma decimal → meal consumption snapshot → water → checkin → overnight sleep → capability → reload → second device',counts:Object.fromEntries(['foods','meals','hydrations','checkins','sleeps','capabilitys'].map(k=>[k,snapshot[k].length])),errors},null,2));console.log('Nutrition, health, capability browser journey: PASS');
}catch(e){if(page&&!page.isClosed()){await page.screenshot({path:root+'/docs/evidence/stage-4/failure.png',fullPage:true});console.error(await page.locator('body').innerText());console.error('STATE',JSON.stringify(await api('bootstrap')))}throw e}finally{if(browser)await browser.close();if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r))}execFileSync(python,['tools/v2/test_database.py','drop',name],{cwd:root})}
