import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync,readFileSync,rmSync} from 'node:fs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10005',name='alos_test_model_'+Date.now();let server,browser,asset;const errors=[];
try{
 execFileSync(python,['tools/v2/test_database.py','create',name],{cwd:root});asset=JSON.parse(execFileSync(python,['tools/v2/synthetic_model_setup.py',name],{cwd:root,encoding:'utf8'}));
 server=spawn(python,['-m','uvicorn','alos.main:create_app','--factory','--host','127.0.0.1','--port','10005','--no-access-log'],{cwd:root,env:{...process.env,PYTHONPATH:root+'/apps/api',ALOS_V2_ENABLED:'1',ALOS_V2_ENVIRONMENT:'test',ALOS_V2_PUBLIC_ORIGIN:base,ALOS_V2_DATABASE_URL:'postgresql://localhost:15432/'+name,ALOS_V2_BODY_MODEL_PATH:asset.path,ALOS_V2_BODY_MODEL_OWNER_ID:asset.owner},stdio:'ignore'});
 for(let i=0;i<80;i++){try{if((await fetch(base+'/health/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({executablePath:process.env.ALOS_BROWSER_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill('deniz');await page.getByLabel('Şifre',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible();
 await page.goto(base+'/#reports');await page.getByRole('button',{name:'3B kütüphanemi aç',exact:true}).click();await expect(page.getByRole('button',{name:'Önden',exact:true})).toBeVisible({timeout:15000});await expect(page.locator('.body-model-canvas canvas')).toBeVisible();await page.getByRole('button',{name:'Arkadan',exact:true}).click();await page.getByRole('button',{name:'Önden',exact:true}).click();await page.screenshot({path:root+'/docs/evidence/stage-6/synthetic-3d.png',fullPage:true});
 await page.reload();await page.getByRole('button',{name:'3B kütüphanemi aç',exact:true}).click();await expect(page.getByRole('button',{name:'Önden',exact:true})).toBeVisible();
 const syntheticBuffer=readFileSync(asset.path);writeFileSync(asset.path,'broken synthetic GLB');await page.reload();await page.getByRole('button',{name:'3B kütüphanemi aç',exact:true}).click();await expect(page.getByRole('button',{name:'3B modeli yeniden dene',exact:true})).toBeVisible();await page.getByRole('button',{name:'Ana sayfaya dön',exact:true}).click();await expect(page.getByRole('heading',{name:'Merhaba, Deniz.'})).toBeVisible();
 await page.goto(base+'/#reports');await page.getByRole('button',{name:'3B kütüphanemi aç',exact:true}).click();await page.getByLabel('Kalıcı 3B model ekle (GLB, en fazla 8 MB)',{exact:true}).setInputFiles({name:'synthetic.glb',mimeType:'model/gltf-binary',buffer:syntheticBuffer});await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Önden',exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'3B kütüphanemi aç',exact:true}).click();await expect(page.locator('.body-model-canvas canvas')).toBeVisible();expect(await page.evaluate(async()=> (await(await fetch('/api/v2/body-model')).json()).status)).toBe('uploaded');
 expect(errors).toEqual([]);writeFileSync(root+'/docs/evidence/stage-6/model-browser-results.json',JSON.stringify({result:'PASS',browser:browser.version(),fixture:'Synthetic triangle only; no real GLB read',checks:['Owner library file loads in WebGL','Camera controls and reload','Broken file retains navigation and record access','UI upload persists in PostgreSQL and opens after reload'],errors},null,2));console.log('Synthetic owner-scoped 3D and fallback browser: PASS');
}finally{if(browser)await browser.close();if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r))}if(asset)rmSync(asset.path);execFileSync(python,['tools/v2/test_database.py','drop',name],{cwd:root})}
