import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10005',name='alos_test_reports_'+Date.now();let server,browser,page;const errors=[];
async function api(path,body){return page.evaluate(async({path,body})=>{const me=await(await fetch('/api/v2/auth/me')).json();const r=await fetch('/api/v2/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':me.csrf},body:JSON.stringify(body)}:{});if(!r.ok)throw Error(await r.text());return r.json()},{path,body})}
async function synced(){await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible({timeout:20000})}
try{
 execFileSync(python,['tools/v2/test_database.py','create',name],{cwd:root});server=spawn(python,['-m','uvicorn','alos.main:create_app','--factory','--host','127.0.0.1','--port','10005','--no-access-log'],{cwd:root,env:{...process.env,PYTHONPATH:root+'/apps/api',ALOS_V2_ENABLED:'1',ALOS_V2_ENVIRONMENT:'test',ALOS_V2_PUBLIC_ORIGIN:base,ALOS_V2_DATABASE_URL:process.env.ALOS_TEST_BACKEND==='mongodb'?'mongodb://127.0.0.1:27028/?replicaSet=alos-test':'postgresql://localhost:15432/'+name,ALOS_V2_MONGO_DATABASE:name},stdio:'ignore'});for(let i=0;i<80;i++){try{if((await fetch(base+'/health/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({executablePath:process.env.ALOS_BROWSER_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill('deniz');await page.getByLabel('Şifre',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await synced();


 const command=(command_type,payload,entity_id=crypto.randomUUID(),expected_version=0)=>({operation_id:crypto.randomUUID(),entity_id,expected_version,schema_version:1,command_type,payload});
 const session=(await api('commands',command('session.open',{local_date:'2026-09-15',title:'Synthetic pull session'}))).entity;
 const actual=(await api('commands',command('set.save',{session_id:session.id,movement_id:'Weighted Pull-Up',name:'Weighted Pull-Up',modality:'strength',reps:5,external_kg:20,status:'completed',local_time:'12:00'}))).entity;
 await page.goto(base+'/?date=2026-09-15#reports');await expect(page.getByRole('heading',{name:'Kas bölgeleri',exact:true})).toBeVisible();await page.getByLabel('İncelenecek kas bölgesi',{exact:true}).selectOption('lats');await expect(page.getByText('Kanat',{exact:true}).last()).toBeVisible();await expect(page.locator('.muscle-readout')).toContainText('ağırlıklı gerçek set');
 await page.getByRole('button',{name:'Kararı geçmişime kaydet',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).analysiss.length).toBe(1);
 await page.screenshot({path:root+'/docs/evidence/stage-5/reports-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const before=await api('bootstrap');const integrity=await api('system/integrity',{});expect(integrity.results.every(r=>r.status==='PASS')).toBe(true);expect((await api('bootstrap')).cursor).toBe(before.cursor);
 await api('commands',command('set.delete',{},actual.id,actual.version));await page.reload();await expect(page.getByText('Hareketi ve miktarı eşleşen gerçek yük kaydı yok.',{exact:true})).toBeVisible();expect((await api('bootstrap')).analysiss.length).toBe(1);
 const {default:AxeBuilder}=await import('../../apps/web/node_modules/@axe-core/playwright/dist/index.mjs');const axe=await new AxeBuilder({page}).analyze();writeFileSync(root+'/docs/evidence/stage-5/a11y.json',JSON.stringify(axe.violations,null,2));expect(axe.violations).toEqual([]);expect(errors).toEqual([]);
 writeFileSync(root+'/docs/evidence/stage-5/browser-results.json',JSON.stringify({result:'PASS',browser:browser.version(),viewport:[390,844],checks:['Real set → muscle exposure → immutable decision','Set delete → fresh report removes load; saved decision stays','Synthetic integrity leaves live owner cursor unchanged','Mobile layout and axe'],errors},null,2));console.log('Reports and source-to-metric browser journey: PASS');
}catch(e){if(page&&!page.isClosed()){await page.screenshot({path:root+'/docs/evidence/stage-5/failure.png',fullPage:true});console.error(await page.locator('body').innerText());console.error('STATE',JSON.stringify(await api('bootstrap')))}throw e}finally{if(browser)await browser.close();if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r))}execFileSync(python,['tools/v2/test_database.py','drop',name],{cwd:root})}
