import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10005';
const names=['alos_test_restore_a_'+Date.now(),'alos_test_restore_b_'+Date.now()];let server,browser,lastPage;
async function start(name){const env={...process.env,PYTHONPATH:root+'/apps/api',ALOS_V2_ENABLED:'1',ALOS_V2_ENVIRONMENT:'test',ALOS_V2_PUBLIC_ORIGIN:base,ALOS_V2_DATABASE_URL:'postgresql://localhost:15432/'+name};server=spawn(python,['-m','uvicorn','alos.main:create_app','--factory','--host','127.0.0.1','--port','10005','--no-access-log'],{cwd:root,env,stdio:'ignore'});for(let i=0;i<80;i++){try{if((await fetch(base+'/health/ready')).ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('startup')}
async function stop(){if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r));server=null}}
async function login(){const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();lastPage=page;page.on('pageerror',e=>console.error('PAGEERROR',e.message));await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill('deniz');await page.getByLabel('Şifre',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await expect(page.getByRole('heading',{name:'Merhaba, Deniz.'})).toBeVisible();return page}
async function api(page,path,body){return page.evaluate(async({path,body})=>{const me=await(await fetch('/api/v2/auth/me')).json();const r=await fetch('/api/v2/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':me.csrf},body:JSON.stringify(body)}:{});if(!r.ok)throw Error(await r.text());return r.json()},{path,body})}
function cmd(type,payload){return{operation_id:crypto.randomUUID(),entity_id:crypto.randomUUID(),expected_version:0,schema_version:1,command_type:type,payload}}
const legacy={app:'Athlete Life OS',data:{scheduleByDate:{'2026-09-15':{shift:'14-22'}},trainingLogs:{'2026-09-10':[{movement:'Pull-up',reps:5}]},guidedWorkoutHistory:[{id:'old-run',status:'completed',date:'2026-09-10'}],foodLogs:{'2026-09-10':[{name:'Oats',grams:60}]},waterLogs:{'2026-09-10':[{ml:500}]},capabilityRecords:[{name:'Ring muscle-up',value:3,unit:'reps'}],newUnknownField:{kept:true}}};
try{
 for(const n of names)execFileSync(python,['tools/v2/test_database.py','create',n],{cwd:root});await start(names[0]);browser=await chromium.launch({executablePath:process.env.ALOS_BROWSER_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const a=await login();await api(a,'commands',cmd('shift.save',{local_date:'2026-09-15',status:'work',start_local:'14:00',end_local:'22:00'}));
 const png=await a.evaluate(()=>{const c=document.createElement('canvas');c.width=20;c.height=20;const x=c.getContext('2d');x.fillStyle='#327';x.fillRect(0,0,20,20);return c.toDataURL('image/png')});await api(a,'commands',cmd('media.save',{name:'Sentetik fotoğraf',content:png}));
 await a.goto(base+'/#backups');await a.getByLabel('JSON veya .alosbackup veri yedeği').setInputFiles({name:'test.alosbackup',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await expect(a.getByRole('heading',{name:'Aktarım önizlemesi'})).toBeVisible();await a.getByRole('button',{name:'Aktarımı onayla'}).click();await expect(a.getByText('trainingLogs · /trainingLogs/2026-09-10/0',{exact:true})).toBeVisible();
 const download=await Promise.all([a.waitForEvent('download'),a.getByRole('button',{name:'Tam yedeği indir',exact:true}).click()]);const path=await download[0].path();await stop();const started=Date.now();await start(names[1]);const b=await login();await b.goto(base+'/#backups');await b.getByLabel('JSON veya .alosbackup veri yedeği').setInputFiles(path);await expect(b.getByRole('heading',{name:'Aktarım önizlemesi'})).toBeVisible();await b.getByRole('button',{name:'Aktarımı onayla'}).click();
 for(const domain of ['trainingLogs','guidedWorkoutHistory','foodLogs','waterLogs','capabilityRecords']){await b.getByLabel('Kayıt grubu',{exact:true}).selectOption(domain);await expect(b.locator('details').first()).toContainText(domain);await b.locator('details').first().locator('summary').click();await expect(b.locator('details').first().locator('pre')).toBeVisible()}
 await expect(b.getByRole('img',{name:'Sentetik fotoğraf'})).toBeVisible();expect(await b.getByRole('img',{name:'Sentetik fotoğraf'}).evaluate(img=>img.naturalWidth)).toBe(20);await b.screenshot({path:root+'/docs/evidence/stage-2/restored-archive.png',fullPage:true});await b.goto(base+'/?date=2026-09-15#week');const day=b.locator('.shift-day').filter({has:b.getByRole('heading',{name:'15 Eylül Salı',exact:true})});await expect(day.getByLabel('Başlangıç')).toHaveValue('14:00');const rtoMs=Date.now()-started;writeFileSync(root+'/docs/evidence/stage-2/restore-browser.json',JSON.stringify({result:'PASS',browser:browser.version(),independentPostgresDatabases:true,rtoMs,rpo:'0 canonical records at export; pending retained separately',paths:['shift','legacy workout/runner','meal','water','capability','private photo'],limits:'Legacy records currently open through archive; domain adapters follow in stages 3/4.'},null,2));console.log('Independent DB restore, UI histories + shift + media: PASS; measured '+rtoMs+' ms');
}catch(e){if(lastPage){await lastPage.screenshot({path:root+'/docs/evidence/stage-2/restore-failure.png',fullPage:true});console.error('BODY',await lastPage.locator('body').innerText());}throw e}finally{if(browser)await browser.close();await stop();for(const n of names)execFileSync(python,['tools/v2/test_database.py','drop',n],{cwd:root})}
