import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10005',name='alos_test_revision_'+Date.now();
let server,browser,page;const results=[],errors=[];
const secret=randomBytes(24).toString('base64url');
async function synced(){await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible({timeout:20000});}
async function api(path,body){return page.evaluate(async({path,body})=>{const me=await(await fetch('/api/v2/auth/me')).json();const r=await fetch('/api/v2/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':me.csrf},body:JSON.stringify(body)}:{});if(!r.ok)throw Error('Synthetic API failed: '+r.status);return r.json()},{path,body});}
try{
 execFileSync(python,['tools/v2/test_database.py','create',name],{cwd:root,stdio:'pipe'});
 execFileSync(python,['-c',`import sys,json;sys.path.insert(0,'apps/api');from alos.db import Database;from alos.auth import create_user;v=json.load(sys.stdin);d=Database('postgresql+psycopg://localhost:15432/'+v['name']);\nwith d.sessions.begin() as s:create_user(s,'revision','Sentetik Revizyon',v['secret'])\nd.engine.dispose()`],{cwd:root,input:JSON.stringify({name,secret}),stdio:['pipe','pipe','pipe']});
 server=spawn(python,['-m','uvicorn','alos.main:create_app','--factory','--host','127.0.0.1','--port','10005','--no-access-log'],{cwd:root,env:{...process.env,PYTHONPATH:root+'/apps/api',ALOS_V2_ENABLED:'1',ALOS_V2_ENVIRONMENT:'test',ALOS_V2_PUBLIC_ORIGIN:base,ALOS_V2_DATABASE_URL:'postgresql://localhost:15432/'+name},stdio:'ignore'});
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill('revision');await page.getByLabel('Şifre',{exact:true}).fill(secret);await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await synced();
 await page.goto(base+'/#profile');await page.getByLabel('Spor geçmişim',{exact:true}).selectOption('regular');const profileForm=page.locator('form').filter({has:page.getByLabel('Spor geçmişim',{exact:true})});await profileForm.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();
 await page.goto(base+'/#program');await page.getByRole('button',{name:'Dönem oluştur',exact:true}).click();await page.getByLabel('Dönem adı',{exact:true}).fill('Sentetik dört hafta');await page.getByLabel('Başlangıç tarihi',{exact:true}).fill('2026-09-07');await page.getByLabel('Dönem sonunda neyi geliştirmek istiyorsun?',{exact:true}).fill('Kayıtlı kuvvet çalışmamı izlemek');const thursday=page.locator('.plan-day').filter({has:page.locator('summary strong',{hasText:'Perşembe'})});await thursday.locator(':scope > summary').click();await thursday.getByLabel('Perşembe türü',{exact:true}).selectOption('training');await thursday.getByRole('button',{name:'Hareket / set / interval ekle',exact:true}).click();await thursday.getByLabel('Katalogdan hareket seç',{exact:true}).selectOption('barbell-squat');await thursday.getByLabel('Set / tur',{exact:true}).fill('9');await thursday.getByLabel('Tekrar',{exact:true}).fill('10');const moveRow=page.locator('.plan-day').nth(3);await moveRow.getByText('Günü taşıma önizlemesi',{exact:true}).click();await moveRow.getByLabel('Yeni gün',{exact:true}).selectOption('1');await moveRow.getByRole('button',{name:'Uygunluğu kontrol et',exact:true}).click();await expect(moveRow.getByText('Vardiya girilmedi. Uygun saat varsayılmadı.',{exact:false})).toBeVisible();await moveRow.getByRole('button',{name:'Bu gün değişimini taslağa uygula',exact:true}).click();await expect(moveRow.locator(':scope > summary')).toContainText('Salı');expect((await api('bootstrap')).programs).toHaveLength(0);await moveRow.getByLabel('Yeni gün',{exact:true}).selectOption('3');await moveRow.getByRole('button',{name:'Uygunluğu kontrol et',exact:true}).click();await moveRow.getByRole('button',{name:'Bu gün değişimini taslağa uygula',exact:true}).click();await expect(moveRow.locator(':scope > summary')).toContainText('Perşembe');results.push('AT44: day move preview reports unknown availability, swaps draft without writing server, and can be reversed');await page.getByRole('button',{name:'Taslağı kaydet',exact:true}).click();await synced();await page.getByRole('button',{name:'Ana planım yap',exact:true}).click();await synced();results.push('AT13/AT35: profile and manual canonical program created through mobile UI');
 await page.goto(base+'/?date=2026-09-10#health');await page.getByRole('button',{name:'Vücut ölçümleri',exact:true}).click();const measures=page.locator('section').filter({has:page.getByRole('heading',{name:'Vücut ölçümleri',exact:true})});await measures.getByRole('button',{name:'Ekle',exact:true}).click();await measures.locator('select[name="metric"]').selectOption('height');await expect(measures.locator('[name="unit"]')).toHaveValue('cm');await measures.locator('[name="value"]').fill('180');await measures.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();expect((await api('bootstrap')).measurements[0].unit).toBe('cm');results.push('AT08: metric changes kg to cm; persisted 180 cm');
 await page.goto(base+'/?date=2026-09-10#workout');await page.getByRole('button',{name:'Günün reçetesini hazırla',exact:true}).click();await synced();await page.getByRole('button',{name:'Yeni seans aç',exact:true}).click();await synced();await expect(page.locator('.set-form')).toBeVisible();const form=page.locator('.set-form');await expect(form.getByRole('heading',{name:'Barbell Squat',exact:true})).toBeVisible();await form.locator('[name="reps"]').fill('10');await form.locator('[name="external_kg"]').fill('60');await form.getByText('Efor, set türü ve diğer ayrıntılar',{exact:true}).click();await form.locator('[name="rir"]').fill('2');await form.locator('[name="set_kind"]').selectOption('working');await form.getByRole('button',{name:'Gerçek seti kaydet',exact:true}).click();await synced();let state=await api('bootstrap');expect(state.sets[0].movement_id).toBe('barbell-squat');expect(state.sets[0].local_date).toBe('2026-09-10');expect(state.sets[0].set_kind).toBe('working');results.push('AT02/AT07/AT37: canonical set, past date and working type survive ACK');
 const stableSession=state.sessions[0].id;await page.goto(base+'/?date=2026-09-11&session='+stableSession+'#workout');await synced();expect((await api('bootstrap')).sessions[0].local_date).toBe('2026-09-10');await page.getByRole('button',{name:'Seansı tamamla',exact:true}).click();await synced();expect((await api('bootstrap')).sets).toHaveLength(1);expect((await api('bootstrap')).slots).toHaveLength(9);results.push('AT06/AT07: one actual from nine targets; finish and selected date change never invent or move records');
 await page.goto(base+'/?date=2026-09-10#reports');await expect(page.getByRole('heading',{name:'Kaydedilen çalışma dağılımı',exact:true})).toBeVisible();await expect(page.getByText('1 / 1 gerçek kayıt kas dağılımına alınabildi.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Seçimimi önizle',exact:true}).click();await expect(page.getByRole('link',{name:'Önizlenen PDF’yi indir',exact:true})).toBeVisible();expect(await page.getByLabel('Hassas sağlık kayıtları',{exact:true}).isChecked()).toBe(false);results.push('AT03/AT52: mapped coverage and opt-in health report');
 await page.goto(base+'/?date=2026-09-11#workout');await page.getByRole('button',{name:'Serbest seans aç',exact:true}).click();await synced();
 for(let i=0;i<3;i++){const f=page.locator('.set-form');await f.getByLabel('Katalogdan hareket seç',{exact:true}).selectOption('barbell-squat');if(i===0){const count=(await api('bootstrap')).sets.length;await f.getByRole('button',{name:'Öncekini kullan',exact:true}).click();await expect(f.locator('[name="external_kg"]')).toHaveValue('60');expect((await api('bootstrap')).sets).toHaveLength(count);results.push('AT36: previous 60 kg fills fields without creating a set');}await f.locator('[name="reps"]').fill('10');await f.locator('[name="external_kg"]').fill('60');await f.getByRole('button',{name:'Gerçek seti kaydet',exact:true}).click();await synced();}
 await page.locator('.record-row').filter({has:page.getByRole('button',{name:'Düzenle',exact:true})}).first().getByRole('button',{name:'Düzenle',exact:true}).click();await page.locator('.set-form [name="reps"]').fill('8');await page.locator('.set-form button[type="submit"]').click();await synced();expect((await api('bootstrap')).sets.filter(r=>r.reps===8)).toHaveLength(1);await page.getByRole('button',{name:'Seansı tamamla',exact:true}).click();await synced();await page.getByText('Seans özeti ve isteğe bağlı geri bildirim',{exact:true}).click();await page.getByLabel('Tüm seansın eforu (0–10)',{exact:true}).fill('6');await page.getByLabel('Gerçek toplam seans süresi (saniye)',{exact:true}).fill('1800');await page.getByRole('button',{name:'Kaydı sakla',exact:true}).click();await synced();await expect(page.getByText('Kaydedilen seans yükü: 180 AU',{exact:false})).toBeVisible();results.push('AT24/AT32: 390×844, three sets, edit one, finish, optional feedback shows 180 AU');
 await page.goto(base+'/#profile');const preferences=page.locator('section').filter({has:page.getByRole('heading',{name:'Planlama tercihlerim',exact:true})});await preferences.getByLabel('Beslenme',{exact:true}).uncheck();await preferences.getByLabel('Uyku',{exact:true}).uncheck();await preferences.getByLabel('Su',{exact:true}).uncheck();await preferences.getByRole('button',{name:'Tercihlerimi kaydet',exact:true}).click();await synced();const ids=(await api('bootstrap')).sets.map(r=>r.id);await page.goto(base+'/#nutrition');await expect(page.getByText('Beslenme · İsteğe bağlı kayıtlarımı aç',{exact:true})).toBeVisible();await expect(page.getByText('Su · İsteğe bağlı kayıtlarımı aç',{exact:true})).toBeVisible();expect((await api('bootstrap')).sets.map(r=>r.id)).toEqual(ids);results.push('AT53: optional modules collapse without deleting records');
 const {default:AxeBuilder}=await import('../../apps/web/node_modules/@axe-core/playwright/dist/index.mjs');
 for(const width of [360,390,768,1280]){
  await page.setViewportSize({width,height:844});
  for(const route of ['today','workout','program','profile','reports','backups']){
   await page.goto(base+'/?date=2026-09-10#'+route);await page.locator('.page-enter').waitFor();await page.locator('.page-enter').evaluate(async e=>{await Promise.all(e.getAnimations({subtree:true}).map(a=>a.finished));});
   expect(await page.evaluate(()=>innerWidth)).toBe(width);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  }
  results.push('AT54: actual viewport '+width+'px; six critical pages without horizontal overflow');
 }
 await page.goto(base+'/#profile');await page.locator('.page-enter').evaluate(async e=>{await Promise.all(e.getAnimations({subtree:true}).map(a=>a.finished));});const a11y=await new AxeBuilder({page}).analyze();writeFileSync(root+'/docs/evidence/revision-v2/a11y.json',JSON.stringify(a11y.violations,null,2));expect(a11y.violations).toEqual([]);
 await page.getByRole('button',{name:'Açık tema; koyu temaya geç',exact:true}).click();const darkA11y=await new AxeBuilder({page}).analyze();expect(darkA11y.violations).toEqual([]);await page.getByRole('button',{name:'Koyu tema; açık temaya geç',exact:true}).click();await page.setViewportSize({width:360,height:844});await page.evaluate(()=>document.documentElement.style.fontSize='32px');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>document.documentElement.style.fontSize='');await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement!==document.body)).toBe(true);results.push('AT33/AT54: light and dark profile axe checks, 200% base text and keyboard focus');
 await page.route('**/*.glb',route=>route.abort());await page.goto(base+'/?date=2026-09-10#reports');await expect(page.getByRole('heading',{name:'Kaydedilen çalışma dağılımı',exact:true})).toBeVisible();results.push('AT33: core report remains available while GLB requests are blocked');await page.unroute('**/*.glb');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/?date=2026-09-10#reports');await page.getByRole('heading',{name:'Kaydedilen çalışma dağılımı'}).waitFor();await page.screenshot({path:root+'/docs/evidence/revision-v2/reports-mobile.png',fullPage:true});
 const beforeReload=await api('bootstrap');await api('auth/logout',{});await context.clearCookies();await page.goto(base);await page.evaluate(async()=>{for(const info of await indexedDB.databases())if(info.name)await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(info.name);r.onsuccess=resolve;r.onerror=reject;r.onblocked=resolve;});});await page.reload();await page.getByLabel('Kullanıcı adı',{exact:true}).fill('revision');await page.getByLabel('Şifre',{exact:true}).fill(secret);await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await synced();const afterReload=await api('bootstrap');expect(afterReload.sets.map(r=>r.id)).toEqual(beforeReload.sets.map(r=>r.id));expect(afterReload.profiles[0].experience).toBe('regular');results.push('AT01/AT35: logout, cleared cache and cookies, relogin retains server IDs and profile');
 expect(errors).toEqual([]);writeFileSync(root+'/docs/evidence/revision-v2/browser.json',JSON.stringify({result:'PASS',browser:browser.version(),checks:results,errors},null,2));console.log(JSON.stringify({result:'PASS',checks:results}));
}catch(error){if(page&&!page.isClosed())await page.screenshot({path:root+'/docs/evidence/revision-v2/browser-failure.png',fullPage:true});console.error('Revision browser failed:',error.message);process.exitCode=1;}finally{if(browser)await browser.close();if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r));}execFileSync(python,['tools/v2/test_database.py','drop',name],{cwd:root,stdio:'pipe'});}
