import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync,mkdirSync} from 'node:fs';
import AxeBuilder from '../../apps/web/node_modules/@axe-core/playwright/dist/index.mjs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10011',name='alos_test_sport_browser_'+Date.now();let server,browser,page,created=false;const errors=[],checks=[];
async function synced(){await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible({timeout:20000});}
async function next(){await page.getByRole('button',{name:'Devam',exact:true}).click();}
try{
 try{await fetch(base+'/health/ready');throw Error('Test port occupied');}catch(e){if(e.message==='Test port occupied')throw e;}
 mkdirSync(root+'/docs/evidence/sport-training',{recursive:true});execFileSync(python,['tools/v2/test_database.py','create',name],{stdio:'pipe'});created=true;
 server=spawn(python,['-m','uvicorn','tools.v2.sport_training_fixture:create','--factory','--host','127.0.0.1','--port','10011','--no-access-log'],{env:{...process.env,PYTHONPATH:root+'/apps/api:'+root,PYTHON_DOTENV_DISABLED:'1',STORAGE_BACKEND:'sqlite',ACCOUNT_STORAGE_BACKEND:'sqlite',ALOS_SYNTHETIC_SPORT_DB:name},stdio:'ignore'});
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill('deniz');await page.getByLabel('Şifre',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await synced();await next();
 await page.getByLabel('Çalıştığın branşı ekle',{exact:true}).selectOption('boxing');await page.getByRole('button',{name:'Branş teknikleriyle planla',exact:true}).click();await expect(page.getByRole('button',{name:'Branş tekniği',exact:false})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Uygulama / raunt / saha çalışması',exact:false}).click();await next();
 await page.getByRole('checkbox',{name:'Boks için uygun tesis, ekipman ve güvenlik düzeni hazır',exact:true}).check();await page.getByRole('checkbox',{name:'Branş eğitmenim uygulamaya eşlik edecek',exact:true}).check();await page.getByRole('checkbox',{name:'Gereken partner veya takım mevcut',exact:true}).check();
 for(const label of ['Boks · Jab','Boks · Cross','Boks · Gard ve duruş'])await page.getByRole('checkbox',{name:label,exact:true}).check();
 await expect(page.getByRole('checkbox',{name:'Karate · Gyaku zuki',exact:true})).toHaveCount(0);await page.reload();await synced();await expect(page.getByRole('checkbox',{name:'Boks · Jab',exact:true})).toBeChecked();await expect(page.getByRole('checkbox',{name:'Branş eğitmenim uygulamaya eşlik edecek',exact:true})).toBeChecked();
 checks.push('selected-branch techniques only; prerequisites and choices survive reload');
 for(const width of [390,1280]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).include('.guided-plan').analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);await page.screenshot({path:root+`/docs/evidence/sport-training/techniques-${width}.png`,fullPage:true});}
 await next();await page.getByLabel('Somut hedefin ne?',{exact:true}).fill('Boks temel tekniklerini eğitmenimle çalışmak');await next();await next();await next();await next();
 await expect(page.getByRole('button',{name:'Branş günleri',exact:false})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('region',{name:'Haftalık branş dağılımı'})).toContainText('Boks');await next();
 await page.getByLabel('18 yaş veya üzerindeyim.',{exact:true}).check();await page.getByLabel('Program adı',{exact:true}).fill('Sentetik boks dönemi');await page.getByRole('checkbox',{name:/Bu formdaki planlama bilgilerimin AI taslağı için EVREN/}).check();
 const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/v2/ai-program-drafts'));await page.getByRole('button',{name:'AI ile programımı hazırla',exact:true}).click();const response=await responsePromise;expect(response.status()).toBe(200);const result=await response.json();expect(result.program.ai_origin.prompt_version).toBe('ai-planner-7');expect(result.program.days.flatMap(d=>d.exercises).every(e=>e.movement_id.startsWith('sport-boxing-')&&e.seconds>0&&e.reps===null)).toBe(true);
 await expect(page.getByRole('heading',{name:'Planına göz at',exact:true})).toBeVisible();await page.screenshot({path:root+'/docs/evidence/sport-training/preview.png',fullPage:true});await page.getByRole('button',{name:'Düzenle ve kaydet',exact:true}).click();
 await expect(page.locator('input').filter({visible:true}).first()).toBeVisible();const values=await page.locator('input').evaluateAll(items=>items.map(i=>i.value));expect(values.some(v=>v.startsWith('Boks ·'))).toBe(true);checks.push('synthetic EVREN response through real validation endpoint; timed branch rounds; prefilled final editor');
 await page.evaluate(async ({row})=>{
   const me=await (await fetch('/api/v2/auth/me')).json();
   async function write(command_type,payload){const r=await fetch('/api/v2/commands',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':me.csrf},body:JSON.stringify({operation_id:crypto.randomUUID(),entity_id:crypto.randomUUID(),expected_version:0,schema_version:1,command_type,payload})});if(!r.ok)throw Error('Synthetic command failed '+r.status);return r.json();}
   const current=await write('session.open',{local_date:'2026-09-15',title:'Synthetic branch session'});
   await write('set.save',{session_id:current.entity.id,movement_id:row.movement_id,name:row.name,modality:'circuit',seconds:90,time_precision:'date_only'});
 },{row:result.program.days.flatMap(d=>d.exercises)[0]});
 await page.goto(base+'/?date=2026-09-15#status');await synced();await expect(page.getByRole('region',{name:'Branş çalışma özeti'})).toContainText('Boks');await expect(page.getByRole('region',{name:'Branş çalışma özeti'})).toContainText('1.5 dk');
 await page.setViewportSize({width:390,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const reportAxe=await new AxeBuilder({page}).include('[aria-label="Branş çalışma özeti"]').analyze();expect(reportAxe.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);await page.screenshot({path:root+'/docs/evidence/sport-training/report-mobile.png',fullPage:true});checks.push('recorded technique seconds appear in branch report without invented muscle values');
 expect(errors).toEqual([]);writeFileSync(root+'/docs/evidence/sport-training/browser-results.json',JSON.stringify({result:'PASS',checks,errors,browser:browser.version(),provider:'synthetic'},null,2));console.log('Sport training browser PASS');
}catch(e){if(page){await page.screenshot({path:root+'/docs/evidence/sport-training/failure.png',fullPage:true});console.error((await page.locator('body').innerText()).slice(-6000));}throw e;}finally{if(browser)await browser.close();if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r));}if(created)execFileSync(python,['tools/v2/test_database.py','drop',name],{stdio:'pipe'});}
