import {chromium,expect} from '../../apps/web/node_modules/@playwright/test/index.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
const root=process.cwd(),python=root+'/.venv-v2/bin/python',base='http://127.0.0.1:10005',name='alos_test_workout_'+Date.now();let server,browser,page;const errors=[];
async function api(path,body){return page.evaluate(async({path,body})=>{const me=await(await fetch('/api/v2/auth/me')).json();const r=await fetch('/api/v2/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':me.csrf},body:JSON.stringify(body)}:{});if(!r.ok)throw Error(await r.text());return r.json()},{path,body})}
async function synced(){await expect(page.getByRole('button',{name:'Sunucuya kaydedildi',exact:true})).toBeVisible({timeout:20000})}
try{
 execFileSync(python,['tools/v2/test_database.py','create',name],{cwd:root});server=spawn(python,['-m','uvicorn','alos.main:create_app','--factory','--host','127.0.0.1','--port','10005','--no-access-log'],{cwd:root,env:{...process.env,PYTHONPATH:root+'/apps/api',ALOS_V2_ENABLED:'1',ALOS_V2_ENVIRONMENT:'test',ALOS_V2_PUBLIC_ORIGIN:base,ALOS_V2_DATABASE_URL:process.env.ALOS_TEST_BACKEND==='mongodb'?'mongodb://127.0.0.1:27028/?replicaSet=alos-test':'postgresql://localhost:15432/'+name,ALOS_V2_MONGO_DATABASE:name},stdio:'ignore'});for(let i=0;i<80;i++){try{if((await fetch(base+'/health/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({executablePath:process.env.ALOS_BROWSER_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByLabel('Kullanıcı adı',{exact:true}).fill('deniz');await page.getByLabel('Şifre',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Giriş yap',exact:true}).click();await synced();
 await page.goto(base+'/#program');await page.getByRole('button',{name:'Dönem oluştur'}).click();await page.getByLabel('Dönem adı',{exact:true}).fill('Four reliable sets');await page.getByLabel('Başlangıç tarihi',{exact:true}).fill('2026-09-14');await page.getByLabel('Dönem sonunda neyi geliştirmek istiyorsun?',{exact:true}).fill('Controlled ring pull-ups');const tuesday=page.locator('.plan-day').filter({has:page.locator('summary strong',{hasText:'Salı'})});await tuesday.locator('summary').click();await tuesday.getByLabel('Salı türü',{exact:true}).selectOption('training');await tuesday.getByRole('button',{name:'Hareket / set / interval ekle'}).click();await tuesday.getByLabel('Hareket adı',{exact:true}).fill('Ring Pull-up');await tuesday.getByLabel('Set / tur',{exact:true}).fill('4');await tuesday.getByLabel('Tekrar',{exact:true}).fill('5');await tuesday.getByLabel('Varyasyon / koşul',{exact:true}).fill('rings-strict');await page.getByRole('button',{name:'Taslağı kaydet',exact:true}).click();await synced();await page.getByRole('button',{name:'Ana planım yap',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).programs[0]?.status).toBe('active');
 await page.goto(base+'/?date=2026-09-15#workout');await page.getByRole('button',{name:'Günün reçetesini hazırla'}).click();await synced();await page.getByRole('button',{name:'Yeni seans aç',exact:true}).click();await synced();let state=await api('bootstrap');expect(state.sessions[0].status).toBe('ready');expect(state.prescriptions[0].locked_at).toBeNull();const sessionId=state.sessions[0].id;
 // Two manual entries: actual inputs, not inferred target completion.
 for(let i=0;i<2;i++){await page.locator('.set-form').getByLabel('Tekrar',{exact:true}).fill('5');await page.getByRole('button',{name:'Gerçek seti kaydet',exact:true}).click();await synced();await expect.poll(async()=> (await api('bootstrap')).sets.length).toBe(i+1)}
 state=await api('bootstrap');expect(state.sets.length).toBe(2);expect(state.prescriptions[0].locked_at).not.toBeNull();
 await context.setOffline(true);await page.getByRole('button',{name:'Hedefi aynen tamamladım',exact:true}).click();await expect(page.getByRole('button',{name:'1 kayıt eşitlenmeyi bekliyor'})).toBeVisible();await page.close();await context.setOffline(false);page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/?date=2026-09-15&session='+sessionId+'#workout');await synced();await expect.poll(async()=> (await api('bootstrap')).sets.length,{timeout:20000}).toBe(3);await expect(page.locator('.runner-progress strong')).toHaveText('3');
 await page.getByRole('button',{name:'Dinlenmeyi başlat',exact:true}).click();await synced();state=await api('bootstrap');expect(state.sessions[0].timer_deadline).not.toBeNull();await page.reload();await synced();await expect(page.getByRole('timer')).not.toHaveText('00:00');await page.getByRole('button',{name:'Süreyi sıfırla',exact:true}).click();await synced();expect((await api('bootstrap')).sets.length).toBe(3);
 await page.screenshot({path:root+'/docs/evidence/stage-3/runner-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);writeFileSync(root+'/docs/evidence/stage-3/browser-results.json',JSON.stringify({result:'PASS',journey:'Manual program UI → approve → prescription → ready view → 2 manual sets → offline third → tab closes → reconnect → exactly 3 → timer reload/reset keeps sets',browser:browser.version(),viewport:[390,844],errors},null,2));console.log('Program + canonical Runner golden journey: PASS');
}catch(e){if(page&&!page.isClosed()){await page.screenshot({path:root+'/docs/evidence/stage-3/failure.png',fullPage:true});console.error(await page.locator('body').innerText());console.error('STATE',JSON.stringify(await api('bootstrap')))}throw e}finally{if(browser)await browser.close();if(server){server.kill('SIGKILL');await new Promise(r=>server.once('exit',r))}execFileSync(python,['tools/v2/test_database.py','drop',name],{cwd:root})}
