"""preserve unknown legacy meal mass"""

import sqlalchemy as sa
from alembic import op

revision = "09797f7a6fd2"
down_revision = "b525cbc4e8af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("meal_entries", "grams", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("meal_entries", "grams", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    # ### end Alembic commands ###
