"""reliable_core"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "6079f0a95359"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("reset_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("auth_epoch", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "athletes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("week_start", sa.Integer(), nullable=False),
        sa.Column("day_boundary_hour", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("generation", sa.UUID(), nullable=False),
        sa.CheckConstraint("day_boundary_hour BETWEEN 0 AND 23"),
        sa.CheckConstraint("week_start BETWEEN 0 AND 6"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("csrf", sa.String(length=64), nullable=False),
        sa.Column("auth_epoch", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "audit_records",
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("command", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("athlete_id", "operation_id"),
    )
    op.create_table(
        "change_log",
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("athlete_id", "sequence"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("athlete_id", "operation_id"),
    )
    op.create_table(
        "optimization_runs",
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("input_sequence", sa.BigInteger(), nullable=False),
        sa.Column("model_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_lineage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("status IN ('proposed','accepted','stale')"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(
        op.f("ix_optimization_runs_athlete_id"), "optimization_runs", ["athlete_id"], unique=False
    )
    op.create_index(
        op.f("ix_optimization_runs_week_start"), "optimization_runs", ["week_start"], unique=False
    )
    op.create_table(
        "shifts",
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("start_local", sa.String(length=5), nullable=True),
        sa.Column("end_local", sa.String(length=5), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_fold", sa.Integer(), nullable=False),
        sa.Column("end_fold", sa.Integer(), nullable=False),
        sa.Column("social", sa.String(length=500), nullable=False),
        sa.Column("commute_min", sa.Integer(), nullable=False),
        sa.Column("prep_min", sa.Integer(), nullable=False),
        sa.Column("sleep_target_min", sa.Integer(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "status != 'work' OR (start_at IS NOT NULL AND end_at IS NOT NULL AND end_at > start_at)"
        ),
        sa.CheckConstraint("status IN ('work','off','annual')"),
        sa.CheckConstraint("commute_min >= 0 AND prep_min >= 0 AND sleep_target_min > 0"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
        sa.UniqueConstraint("athlete_id", "local_date"),
    )
    op.create_index(op.f("ix_shifts_athlete_id"), "shifts", ["athlete_id"], unique=False)
    op.create_table(
        "transactional_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "operation_id", "topic"),
    )
    op.create_index(
        op.f("ix_transactional_outbox_athlete_id"), "transactional_outbox", ["athlete_id"], unique=False
    )
    op.create_index(
        "outbox_available", "transactional_outbox", ["processed_at", "available_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("outbox_available", table_name="transactional_outbox")
    op.drop_index(op.f("ix_transactional_outbox_athlete_id"), table_name="transactional_outbox")
    op.drop_table("transactional_outbox")
    op.drop_index(op.f("ix_shifts_athlete_id"), table_name="shifts")
    op.drop_table("shifts")
    op.drop_index(op.f("ix_optimization_runs_week_start"), table_name="optimization_runs")
    op.drop_index(op.f("ix_optimization_runs_athlete_id"), table_name="optimization_runs")
    op.drop_table("optimization_runs")
    op.drop_table("idempotency_keys")
    op.drop_table("change_log")
    op.drop_table("audit_records")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("athletes")
    op.drop_table("users")
    op.drop_table("login_attempts")
    # ### end Alembic commands ###
