"""backups_and_legacy_archive"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "a346366076dc"
down_revision = "6079f0a95359"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_objects",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("mime", sa.String(length=80), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_media_objects_athlete_id"), "media_objects", ["athlete_id"], unique=False)
    op.create_table(
        "migration_runs",
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("format", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("status IN ('staged','applied','quarantined')"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
        sa.UniqueConstraint("athlete_id", "source_digest"),
    )
    op.create_index(op.f("ix_migration_runs_athlete_id"), "migration_runs", ["athlete_id"], unique=False)
    op.create_table(
        "legacy_extensions",
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("pointer", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("time_precision", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id", "import_id"],
            ["migration_runs.athlete_id", "migration_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
        sa.UniqueConstraint("athlete_id", "import_id", "pointer"),
    )
    op.create_index(
        op.f("ix_legacy_extensions_athlete_id"), "legacy_extensions", ["athlete_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_legacy_extensions_athlete_id"), table_name="legacy_extensions")
    op.drop_table("legacy_extensions")
    op.drop_index(op.f("ix_migration_runs_athlete_id"), table_name="migration_runs")
    op.drop_table("migration_runs")
    op.drop_index(op.f("ix_media_objects_athlete_id"), table_name="media_objects")
    op.drop_table("media_objects")
    # ### end Alembic commands ###
