"""canonical_workout_execution"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "aa6bbe429c70"
down_revision = "a346366076dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "program_versions",
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("goal", sa.String(length=1000), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("weeks", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("decisions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("status IN ('draft','active','archived','completed')"),
        sa.CheckConstraint("weeks BETWEEN 1 AND 52"),
        sa.ForeignKeyConstraint(
            ["athlete_id", "parent_id"],
            ["program_versions.athlete_id", "program_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_program_versions_athlete_id"), "program_versions", ["athlete_id"], unique=False)
    op.create_table(
        "weekly_slots",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("kind IN ('training','rest')"),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6"),
        sa.ForeignKeyConstraint(
            ["athlete_id", "program_id"],
            ["program_versions.athlete_id", "program_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_weekly_slots_athlete_id"), "weekly_slots", ["athlete_id"], unique=False)
    op.create_table(
        "program_exercises",
        sa.Column("day_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("movement_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("variant", sa.String(length=150), nullable=False),
        sa.Column("modality", sa.String(length=20), nullable=False),
        sa.Column("equipment", sa.String(length=100), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("load_kind", sa.String(length=20), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("seconds", sa.Float(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("external_kg", sa.Float(), nullable=True),
        sa.Column("assistance_kg", sa.Float(), nullable=True),
        sa.Column("bodyweight_kg", sa.Float(), nullable=True),
        sa.Column("rir", sa.Float(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("sets BETWEEN 1 AND 30"),
        sa.ForeignKeyConstraint(
            ["athlete_id", "day_id"],
            ["weekly_slots.athlete_id", "weekly_slots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(
        op.f("ix_program_exercises_athlete_id"), "program_exercises", ["athlete_id"], unique=False
    )
    op.create_table(
        "session_prescriptions",
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column("day_id", sa.UUID(), nullable=True),
        sa.Column("program_version", sa.Integer(), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id", "day_id"],
            ["weekly_slots.athlete_id", "weekly_slots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id", "program_id"],
            ["program_versions.athlete_id", "program_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "day_id", "scheduled_date"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(
        op.f("ix_session_prescriptions_athlete_id"), "session_prescriptions", ["athlete_id"], unique=False
    )
    op.create_table(
        "prescription_set_slots",
        sa.Column("prescription_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("set_index", sa.Integer(), nullable=False),
        sa.Column("movement_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("variant", sa.String(length=150), nullable=False),
        sa.Column("modality", sa.String(length=20), nullable=False),
        sa.Column("equipment", sa.String(length=100), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("load_kind", sa.String(length=20), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("seconds", sa.Float(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("external_kg", sa.Float(), nullable=True),
        sa.Column("assistance_kg", sa.Float(), nullable=True),
        sa.Column("bodyweight_kg", sa.Float(), nullable=True),
        sa.Column("rir", sa.Float(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id", "prescription_id"],
            ["session_prescriptions.athlete_id", "session_prescriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
        sa.UniqueConstraint("athlete_id", "prescription_id", "ordinal"),
    )
    op.create_index(
        op.f("ix_prescription_set_slots_athlete_id"), "prescription_set_slots", ["athlete_id"], unique=False
    )
    op.create_table(
        "workout_sessions",
        sa.Column("prescription_id", sa.UUID(), nullable=True),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timer_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timer_remaining_ms", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("status IN ('draft','ready','active','paused','completed','abandoned')"),
        sa.ForeignKeyConstraint(
            ["athlete_id", "prescription_id"],
            ["session_prescriptions.athlete_id", "session_prescriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_workout_sessions_athlete_id"), "workout_sessions", ["athlete_id"], unique=False)
    op.create_table(
        "performed_sets",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("slot_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("movement_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("variant", sa.String(length=150), nullable=False),
        sa.Column("modality", sa.String(length=20), nullable=False),
        sa.Column("equipment", sa.String(length=100), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("load_kind", sa.String(length=20), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("seconds", sa.Float(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("external_kg", sa.Float(), nullable=True),
        sa.Column("assistance_kg", sa.Float(), nullable=True),
        sa.Column("bodyweight_kg", sa.Float(), nullable=True),
        sa.Column("rir", sa.Float(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("status IN ('completed','skipped','extra','substituted')"),
        sa.CheckConstraint(
            "(external_kg IS NULL OR external_kg >= 0) AND (assistance_kg IS NULL OR assistance_kg >= 0) AND (bodyweight_kg IS NULL OR bodyweight_kg > 0)"
        ),
        sa.CheckConstraint(
            "(reps IS NULL OR reps >= 0) AND (seconds IS NULL OR seconds >= 0) AND (distance_m IS NULL OR distance_m >= 0)"
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id", "session_id"],
            ["workout_sessions.athlete_id", "workout_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id", "slot_id"],
            ["prescription_set_slots.athlete_id", "prescription_set_slots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_performed_sets_athlete_id"), "performed_sets", ["athlete_id"], unique=False)
    op.create_index(
        "unique_session_slot_alive",
        "performed_sets",
        ["athlete_id", "session_id", "slot_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND slot_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_session_slot_alive",
        table_name="performed_sets",
        postgresql_where=sa.text("deleted_at IS NULL AND slot_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_performed_sets_athlete_id"), table_name="performed_sets")
    op.drop_table("performed_sets")
    op.drop_index(op.f("ix_workout_sessions_athlete_id"), table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_index(op.f("ix_prescription_set_slots_athlete_id"), table_name="prescription_set_slots")
    op.drop_table("prescription_set_slots")
    op.drop_index(op.f("ix_session_prescriptions_athlete_id"), table_name="session_prescriptions")
    op.drop_table("session_prescriptions")
    op.drop_index(op.f("ix_program_exercises_athlete_id"), table_name="program_exercises")
    op.drop_table("program_exercises")
    op.drop_index(op.f("ix_weekly_slots_athlete_id"), table_name="weekly_slots")
    op.drop_table("weekly_slots")
    op.drop_index(op.f("ix_program_versions_athlete_id"), table_name="program_versions")
    op.drop_table("program_versions")
    # ### end Alembic commands ###
