"""nutrition_daily_capability_health"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "b525cbc4e8af"
down_revision = "aa6bbe429c70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "body_measurements",
        sa.Column("metric", sa.String(length=40), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("protocol", sa.String(length=150), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("value > 0"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(
        op.f("ix_body_measurements_athlete_id"), "body_measurements", ["athlete_id"], unique=False
    )
    op.create_index(
        op.f("ix_body_measurements_local_date"), "body_measurements", ["local_date"], unique=False
    )
    op.create_table(
        "capability_measurements",
        sa.Column("definition_id", sa.String(length=100), nullable=False),
        sa.Column("protocol_version", sa.String(length=60), nullable=False),
        sa.Column("variant", sa.String(length=150), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("equipment", sa.String(length=150), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("selection", sa.String(length=20), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("attempt > 0"),
        sa.CheckConstraint("value IS NULL OR value >= 0"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(
        op.f("ix_capability_measurements_athlete_id"), "capability_measurements", ["athlete_id"], unique=False
    )
    op.create_index(
        op.f("ix_capability_measurements_local_date"), "capability_measurements", ["local_date"], unique=False
    )
    op.create_table(
        "cycle_entries",
        sa.Column("bleeding", sa.String(length=20), nullable=False),
        sa.Column("symptoms", sa.Integer(), nullable=True),
        sa.Column("cycle_day", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("symptoms IS NULL OR symptoms BETWEEN 0 AND 10"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_cycle_entries_athlete_id"), "cycle_entries", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_cycle_entries_local_date"), "cycle_entries", ["local_date"], unique=False)
    op.create_table(
        "daily_checkins",
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("fatigue", sa.Integer(), nullable=True),
        sa.Column("stress", sa.Integer(), nullable=True),
        sa.Column("sleep_quality", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "(energy IS NULL OR energy BETWEEN 0 AND 10) AND (fatigue IS NULL OR fatigue BETWEEN 0 AND 10) AND (stress IS NULL OR stress BETWEEN 0 AND 10) AND (sleep_quality IS NULL OR sleep_quality BETWEEN 0 AND 10)"
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_daily_checkins_athlete_id"), "daily_checkins", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_daily_checkins_local_date"), "daily_checkins", ["local_date"], unique=False)
    op.create_table(
        "food_items",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("kcal", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("carbs_g", sa.Float(), nullable=False),
        sa.Column("fat_g", sa.Float(), nullable=False),
        sa.Column("fiber_g", sa.Float(), nullable=True),
        sa.Column("reference", sa.String(length=500), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("kcal >= 0 AND protein_g >= 0 AND carbs_g >= 0 AND fat_g >= 0"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_food_items_athlete_id"), "food_items", ["athlete_id"], unique=False)
    op.create_table(
        "goals",
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("variant", sa.String(length=150), nullable=False),
        sa.Column("baseline", sa.Float(), nullable=False),
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("target != baseline"),
        sa.CheckConstraint("target_date >= start_date"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_goals_athlete_id"), "goals", ["athlete_id"], unique=False)
    op.create_table(
        "health_episodes",
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("resolved_date", sa.Date(), nullable=True),
        sa.Column("return_until", sa.Date(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=1500), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("resolved_date IS NULL OR resolved_date >= start_date"),
        sa.CheckConstraint("return_until IS NULL OR return_until >= start_date"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_health_episodes_athlete_id"), "health_episodes", ["athlete_id"], unique=False)
    op.create_table(
        "hydration_entries",
        sa.Column("ml", sa.Float(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("ml > 0 AND ml <= 10000"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(
        op.f("ix_hydration_entries_athlete_id"), "hydration_entries", ["athlete_id"], unique=False
    )
    op.create_index(
        op.f("ix_hydration_entries_local_date"), "hydration_entries", ["local_date"], unique=False
    )
    op.create_table(
        "lab_observations",
        sa.Column("analyte", sa.String(length=150), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("reference_low", sa.Float(), nullable=True),
        sa.Column("reference_high", sa.Float(), nullable=True),
        sa.Column("laboratory", sa.String(length=150), nullable=False),
        sa.Column("method", sa.String(length=150), nullable=False),
        sa.Column("fasting", sa.Boolean(), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "reference_low IS NULL OR reference_high IS NULL OR reference_low <= reference_high"
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_lab_observations_athlete_id"), "lab_observations", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_lab_observations_local_date"), "lab_observations", ["local_date"], unique=False)
    op.create_table(
        "life_events",
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("modality", sa.String(length=30), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("duplicate_of", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("kind IN ('social','physical') AND status IN ('planned','occurred','cancelled')"),
        sa.ForeignKeyConstraint(
            ["athlete_id", "duplicate_of"],
            ["life_events.athlete_id", "life_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_life_events_athlete_id"), "life_events", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_life_events_local_date"), "life_events", ["local_date"], unique=False)
    op.create_table(
        "nutrition_day_status",
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("status IN ('complete','partial','not_logged')"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
        sa.UniqueConstraint("athlete_id", "local_date"),
    )
    op.create_index(
        op.f("ix_nutrition_day_status_athlete_id"), "nutrition_day_status", ["athlete_id"], unique=False
    )
    op.create_table(
        "pain_entries",
        sa.Column("area", sa.String(length=100), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("intensity", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("intensity BETWEEN 0 AND 10"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_pain_entries_athlete_id"), "pain_entries", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_pain_entries_local_date"), "pain_entries", ["local_date"], unique=False)
    op.create_table(
        "recipes",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("total_grams", sa.Float(), nullable=False),
        sa.Column("instructions", sa.String(length=3000), nullable=False),
        sa.Column("ingredients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nutrient_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("total_grams > 0"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_recipes_athlete_id"), "recipes", ["athlete_id"], unique=False)
    op.create_table(
        "sleep_entries",
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("quality", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("end_at > start_at"),
        sa.CheckConstraint("quality IS NULL OR quality BETWEEN 0 AND 10"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_sleep_entries_athlete_id"), "sleep_entries", ["athlete_id"], unique=False)
    op.create_table(
        "athlete_profiles",
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("sex", sa.String(length=20), nullable=False),
        sa.Column("experience", sa.String(length=20), nullable=False),
        sa.Column("cycle_tracking", sa.Boolean(), nullable=False),
        sa.Column("interface_mode", sa.String(length=20), nullable=False),
        sa.Column("avatar_id", sa.UUID(), nullable=True),
        sa.Column("equipment", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sport_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tutorial_completed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id", "avatar_id"],
            ["media_objects.athlete_id", "media_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_athlete_profiles_athlete_id"), "athlete_profiles", ["athlete_id"], unique=False)
    op.create_table(
        "goal_measurements",
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id", "goal_id"],
            ["goals.athlete_id", "goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(
        op.f("ix_goal_measurements_athlete_id"), "goal_measurements", ["athlete_id"], unique=False
    )
    op.create_index(
        op.f("ix_goal_measurements_local_date"), "goal_measurements", ["local_date"], unique=False
    )
    op.create_table(
        "meal_entries",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("meal_type", sa.String(length=20), nullable=False),
        sa.Column("grams", sa.Float(), nullable=False),
        sa.Column("food_id", sa.UUID(), nullable=True),
        sa.Column("recipe_id", sa.UUID(), nullable=True),
        sa.Column("source_version", sa.Integer(), nullable=True),
        sa.Column("kcal", sa.Float(), nullable=True),
        sa.Column("protein_g", sa.Float(), nullable=True),
        sa.Column("carbs_g", sa.Float(), nullable=True),
        sa.Column("fat_g", sa.Float(), nullable=True),
        sa.Column("fiber_g", sa.Float(), nullable=True),
        sa.Column("nutrient_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint("food_id IS NULL OR recipe_id IS NULL"),
        sa.CheckConstraint("grams > 0 AND kcal >= 0 AND protein_g >= 0 AND carbs_g >= 0 AND fat_g >= 0"),
        sa.ForeignKeyConstraint(
            ["athlete_id", "food_id"],
            ["food_items.athlete_id", "food_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id", "recipe_id"],
            ["recipes.athlete_id", "recipes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_meal_entries_athlete_id"), "meal_entries", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_meal_entries_local_date"), "meal_entries", ["local_date"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meal_entries_local_date"), table_name="meal_entries")
    op.drop_index(op.f("ix_meal_entries_athlete_id"), table_name="meal_entries")
    op.drop_table("meal_entries")
    op.drop_index(op.f("ix_goal_measurements_local_date"), table_name="goal_measurements")
    op.drop_index(op.f("ix_goal_measurements_athlete_id"), table_name="goal_measurements")
    op.drop_table("goal_measurements")
    op.drop_index(op.f("ix_athlete_profiles_athlete_id"), table_name="athlete_profiles")
    op.drop_table("athlete_profiles")
    op.drop_index(op.f("ix_sleep_entries_athlete_id"), table_name="sleep_entries")
    op.drop_table("sleep_entries")
    op.drop_index(op.f("ix_recipes_athlete_id"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_index(op.f("ix_pain_entries_local_date"), table_name="pain_entries")
    op.drop_index(op.f("ix_pain_entries_athlete_id"), table_name="pain_entries")
    op.drop_table("pain_entries")
    op.drop_index(op.f("ix_nutrition_day_status_athlete_id"), table_name="nutrition_day_status")
    op.drop_table("nutrition_day_status")
    op.drop_index(op.f("ix_life_events_local_date"), table_name="life_events")
    op.drop_index(op.f("ix_life_events_athlete_id"), table_name="life_events")
    op.drop_table("life_events")
    op.drop_index(op.f("ix_lab_observations_local_date"), table_name="lab_observations")
    op.drop_index(op.f("ix_lab_observations_athlete_id"), table_name="lab_observations")
    op.drop_table("lab_observations")
    op.drop_index(op.f("ix_hydration_entries_local_date"), table_name="hydration_entries")
    op.drop_index(op.f("ix_hydration_entries_athlete_id"), table_name="hydration_entries")
    op.drop_table("hydration_entries")
    op.drop_index(op.f("ix_health_episodes_athlete_id"), table_name="health_episodes")
    op.drop_table("health_episodes")
    op.drop_index(op.f("ix_goals_athlete_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_food_items_athlete_id"), table_name="food_items")
    op.drop_table("food_items")
    op.drop_index(op.f("ix_daily_checkins_local_date"), table_name="daily_checkins")
    op.drop_index(op.f("ix_daily_checkins_athlete_id"), table_name="daily_checkins")
    op.drop_table("daily_checkins")
    op.drop_index(op.f("ix_cycle_entries_local_date"), table_name="cycle_entries")
    op.drop_index(op.f("ix_cycle_entries_athlete_id"), table_name="cycle_entries")
    op.drop_table("cycle_entries")
    op.drop_index(op.f("ix_capability_measurements_local_date"), table_name="capability_measurements")
    op.drop_index(op.f("ix_capability_measurements_athlete_id"), table_name="capability_measurements")
    op.drop_table("capability_measurements")
    op.drop_index(op.f("ix_body_measurements_local_date"), table_name="body_measurements")
    op.drop_index(op.f("ix_body_measurements_athlete_id"), table_name="body_measurements")
    op.drop_table("body_measurements")
    # ### end Alembic commands ###
