"""workspace era archives"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "d9403fbd67bd"
down_revision = "3d7726dd00de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_archives",
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("input_revision", sa.BigInteger(), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(
        op.f("ix_workspace_archives_athlete_id"), "workspace_archives", ["athlete_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_archives_athlete_id"), table_name="workspace_archives")
    op.drop_table("workspace_archives")
    # ### end Alembic commands ###
