"""versioned decision snapshots"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "db070d02c399"
down_revision = "09797f7a6fd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_runs",
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=60), nullable=False),
        sa.Column("input_revision", sa.BigInteger(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("knowledge", sa.String(length=30), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "id"),
    )
    op.create_index(op.f("ix_analysis_runs_athlete_id"), "analysis_runs", ["athlete_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_runs_athlete_id"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    # ### end Alembic commands ###
